// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _scaled_fixed2ieee_HH_
#define _scaled_fixed2ieee_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "houghTransform_mubkb.h"

namespace ap_rtl {

struct scaled_fixed2ieee : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<63> > in_V;
    sc_in< sc_lv<13> > prescale;
    sc_out< sc_lv<64> > ap_return;


    // Module declarations
    scaled_fixed2ieee(sc_module_name name);
    SC_HAS_PROCESS(scaled_fixed2ieee);

    ~scaled_fixed2ieee();

    sc_trace_file* mVcdFile;

    houghTransform_mubkb<1,1,32,32,32,32,2,32>* houghTransform_mubkb_U0;
    houghTransform_mubkb<1,1,32,32,32,32,2,32>* houghTransform_mubkb_U1;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<2> > i_1_fu_274_p2;
    sc_signal< sc_lv<2> > i_1_reg_795;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<6> > Hi_assign_fu_288_p2;
    sc_signal< sc_lv<6> > Hi_assign_reg_800;
    sc_signal< sc_lv<1> > exitcond1_fu_268_p2;
    sc_signal< sc_lv<6> > Lo_assign_fu_294_p2;
    sc_signal< sc_lv<6> > Lo_assign_reg_806;
    sc_signal< sc_lv<1> > tmp_20_fu_300_p2;
    sc_signal< sc_lv<1> > tmp_20_reg_814;
    sc_signal< sc_lv<32> > p_Result_29_fu_317_p5;
    sc_signal< sc_lv<32> > p_Result_29_reg_821;
    sc_signal< sc_lv<6> > tmp_28_fu_370_p2;
    sc_signal< sc_lv<6> > tmp_28_reg_826;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<63> > tmp_31_fu_380_p2;
    sc_signal< sc_lv<63> > tmp_31_reg_831;
    sc_signal< sc_lv<32> > out_bits_2_V_1_fu_460_p3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > out_bits_2_V_6_fu_476_p3;
    sc_signal< sc_lv<32> > out_bits_2_V_8_fu_484_p3;
    sc_signal< sc_lv<3> > i_2_fu_498_p2;
    sc_signal< sc_lv<3> > i_2_reg_854;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<2> > tmp_35_fu_504_p1;
    sc_signal< sc_lv<2> > tmp_35_reg_859;
    sc_signal< sc_lv<1> > exitcond_fu_492_p2;
    sc_signal< sc_lv<32> > p_Result_30_fu_521_p4;
    sc_signal< sc_lv<32> > p_Result_30_reg_866;
    sc_signal< sc_lv<32> > c_3_fu_567_p3;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > c_3_3_fu_583_p3;
    sc_signal< sc_lv<32> > c_3_5_fu_591_p3;
    sc_signal< sc_lv<32> > c_3_6_fu_607_p3;
    sc_signal< sc_lv<1> > tmp_36_fu_615_p3;
    sc_signal< sc_lv<1> > tmp_36_reg_891;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<3> > i_3_fu_623_p2;
    sc_signal< sc_lv<3> > i_3_reg_895;
    sc_signal< sc_lv<32> > sh_assign_fu_633_p6;
    sc_signal< sc_lv<32> > sh_assign_reg_900;
    sc_signal< sc_lv<1> > isNeg_fu_647_p3;
    sc_signal< sc_lv<1> > isNeg_reg_906;
    sc_signal< sc_lv<32> > sh_assign_1_fu_661_p3;
    sc_signal< sc_lv<32> > sh_assign_1_reg_911;
    sc_signal< sc_lv<32> > shift_2_fu_669_p2;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<63> > in_shift_V_fu_689_p3;
    sc_signal< sc_lv<12> > tmp_7_fu_704_p2;
    sc_signal< sc_lv<12> > tmp_7_reg_931;
    sc_signal< sc_lv<1> > tmp_6_fu_696_p2;
    sc_signal< sc_lv<1> > tmp_8_fu_710_p2;
    sc_signal< sc_lv<1> > tmp_8_reg_936;
    sc_signal< sc_lv<1> > or_cond_59_fu_732_p2;
    sc_signal< sc_lv<1> > or_cond_59_reg_941;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<11> > tmp_41_fu_737_p1;
    sc_signal< sc_lv<11> > tmp_41_reg_947;
    sc_signal< sc_lv<32> > out_bits_2_V_s_reg_108;
    sc_signal< sc_lv<32> > out_bits_1_V_s_reg_120;
    sc_signal< sc_lv<32> > out_bits_2_V_7_reg_132;
    sc_signal< sc_lv<2> > i_reg_144;
    sc_signal< sc_lv<32> > c_2_s_reg_156;
    sc_signal< sc_lv<32> > c_3_1_reg_168;
    sc_signal< sc_lv<32> > c_3_4_reg_180;
    sc_signal< sc_lv<32> > c_3_s_reg_192;
    sc_signal< sc_lv<3> > i1_reg_204;
    sc_signal< sc_lv<63> > in_shift_reg_215;
    sc_signal< sc_lv<32> > shift_reg_225;
    sc_signal< sc_lv<3> > i2_reg_237;
    sc_signal< sc_lv<32> > shift_1_reg_248;
    sc_signal< sc_lv<63> > p_Val2_s_reg_258;
    sc_signal< sc_lv<6> > tmp_fu_280_p3;
    sc_signal< sc_lv<15> > tmp_19_fu_306_p1;
    sc_signal< sc_lv<16> > tmp_1_fu_309_p3;
    sc_signal< sc_lv<6> > tmp_22_fu_338_p2;
    sc_signal< sc_lv<6> > tmp_24_fu_347_p2;
    sc_signal< sc_lv<63> > tmp_21_fu_329_p4;
    sc_signal< sc_lv<6> > tmp_23_fu_342_p2;
    sc_signal< sc_lv<6> > tmp_25_fu_351_p3;
    sc_signal< sc_lv<6> > tmp_27_fu_364_p3;
    sc_signal< sc_lv<63> > tmp_26_fu_358_p3;
    sc_signal< sc_lv<63> > tmp_29_fu_376_p1;
    sc_signal< sc_lv<63> > tmp_30_fu_386_p1;
    sc_signal< sc_lv<63> > tmp_32_fu_389_p2;
    sc_signal< sc_lv<1> > sel_tmp_fu_400_p2;
    sc_signal< sc_lv<1> > sel_tmp9_fu_414_p2;
    sc_signal< sc_lv<32> > out_bits_2_V_fu_406_p3;
    sc_signal< sc_lv<63> > p_Result_s_fu_395_p2;
    sc_signal< sc_lv<16> > tmp_34_fu_428_p1;
    sc_signal< sc_lv<32> > out_bits_2_V_9_fu_420_p3;
    sc_signal< sc_lv<17> > tmp_3_fu_432_p3;
    sc_signal< sc_lv<32> > p_Result_28_fu_440_p5;
    sc_signal< sc_lv<32> > out_bits_2_V_4_fu_452_p3;
    sc_signal< sc_lv<32> > out_bits_2_V_5_fu_468_p3;
    sc_signal< sc_lv<2> > p_Val2_31_fu_508_p5;
    sc_signal< sc_lv<32> > p_Val2_31_fu_508_p6;
    sc_signal< sc_lv<1> > sel_tmp5_fu_548_p2;
    sc_signal< sc_lv<1> > sel_tmp4_fu_543_p2;
    sc_signal< sc_lv<1> > sel_tmp3_fu_538_p2;
    sc_signal< sc_lv<32> > c_3_8_fu_531_p3;
    sc_signal< sc_lv<1> > or_cond_fu_553_p2;
    sc_signal< sc_lv<32> > newSel_fu_559_p3;
    sc_signal< sc_lv<32> > c_3_2_fu_575_p3;
    sc_signal< sc_lv<32> > newSel2_fu_599_p3;
    sc_signal< sc_lv<2> > sh_assign_fu_633_p5;
    sc_signal< sc_lv<32> > tmp_s_fu_655_p2;
    sc_signal< sc_lv<63> > tmp_2_fu_674_p1;
    sc_signal< sc_lv<63> > tmp_5_fu_683_p2;
    sc_signal< sc_lv<63> > tmp_4_fu_677_p2;
    sc_signal< sc_lv<12> > tmp_39_fu_701_p1;
    sc_signal< sc_lv<32> > tmp_51_cast_fu_715_p1;
    sc_signal< sc_lv<32> > newexp_fu_718_p2;
    sc_signal< sc_lv<1> > tmp_40_fu_724_p3;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<52> > phitmp2_fu_741_p4;
    sc_signal< sc_lv<11> > out_exp_V_fu_758_p3;
    sc_signal< sc_lv<52> > p_Val2_32_fu_751_p3;
    sc_signal< sc_lv<64> > p_Result_31_fu_764_p4;
    sc_signal< sc_lv<64> > result_write_assign_fu_774_p1;
    sc_signal< sc_lv<64> > ap_return_preg;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_fsm_state1;
    static const sc_lv<10> ap_ST_fsm_state2;
    static const sc_lv<10> ap_ST_fsm_state3;
    static const sc_lv<10> ap_ST_fsm_state4;
    static const sc_lv<10> ap_ST_fsm_state5;
    static const sc_lv<10> ap_ST_fsm_state6;
    static const sc_lv<10> ap_ST_fsm_state7;
    static const sc_lv<10> ap_ST_fsm_state8;
    static const sc_lv<10> ap_ST_fsm_state9;
    static const sc_lv<10> ap_ST_fsm_state10;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<6> ap_const_lv6_3E;
    static const sc_lv<6> ap_const_lv6_2F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<63> ap_const_lv63_7FFFFFFFFFFFFFFF;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<12> ap_const_lv12_3FF;
    static const sc_lv<63> ap_const_lv63_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_3D;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<52> ap_const_lv52_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<64> ap_const_lv64_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_Hi_assign_fu_288_p2();
    void thread_Lo_assign_fu_294_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_c_3_2_fu_575_p3();
    void thread_c_3_3_fu_583_p3();
    void thread_c_3_5_fu_591_p3();
    void thread_c_3_6_fu_607_p3();
    void thread_c_3_8_fu_531_p3();
    void thread_c_3_fu_567_p3();
    void thread_exitcond1_fu_268_p2();
    void thread_exitcond_fu_492_p2();
    void thread_i_1_fu_274_p2();
    void thread_i_2_fu_498_p2();
    void thread_i_3_fu_623_p2();
    void thread_in_shift_V_fu_689_p3();
    void thread_isNeg_fu_647_p3();
    void thread_newSel2_fu_599_p3();
    void thread_newSel_fu_559_p3();
    void thread_newexp_fu_718_p2();
    void thread_or_cond_59_fu_732_p2();
    void thread_or_cond_fu_553_p2();
    void thread_out_bits_2_V_1_fu_460_p3();
    void thread_out_bits_2_V_4_fu_452_p3();
    void thread_out_bits_2_V_5_fu_468_p3();
    void thread_out_bits_2_V_6_fu_476_p3();
    void thread_out_bits_2_V_8_fu_484_p3();
    void thread_out_bits_2_V_9_fu_420_p3();
    void thread_out_bits_2_V_fu_406_p3();
    void thread_out_exp_V_fu_758_p3();
    void thread_p_Result_28_fu_440_p5();
    void thread_p_Result_29_fu_317_p5();
    void thread_p_Result_30_fu_521_p4();
    void thread_p_Result_31_fu_764_p4();
    void thread_p_Result_s_fu_395_p2();
    void thread_p_Val2_31_fu_508_p5();
    void thread_p_Val2_32_fu_751_p3();
    void thread_phitmp2_fu_741_p4();
    void thread_result_write_assign_fu_774_p1();
    void thread_sel_tmp3_fu_538_p2();
    void thread_sel_tmp4_fu_543_p2();
    void thread_sel_tmp5_fu_548_p2();
    void thread_sel_tmp9_fu_414_p2();
    void thread_sel_tmp_fu_400_p2();
    void thread_sh_assign_1_fu_661_p3();
    void thread_sh_assign_fu_633_p5();
    void thread_shift_2_fu_669_p2();
    void thread_tmp_19_fu_306_p1();
    void thread_tmp_1_fu_309_p3();
    void thread_tmp_20_fu_300_p2();
    void thread_tmp_21_fu_329_p4();
    void thread_tmp_22_fu_338_p2();
    void thread_tmp_23_fu_342_p2();
    void thread_tmp_24_fu_347_p2();
    void thread_tmp_25_fu_351_p3();
    void thread_tmp_26_fu_358_p3();
    void thread_tmp_27_fu_364_p3();
    void thread_tmp_28_fu_370_p2();
    void thread_tmp_29_fu_376_p1();
    void thread_tmp_2_fu_674_p1();
    void thread_tmp_30_fu_386_p1();
    void thread_tmp_31_fu_380_p2();
    void thread_tmp_32_fu_389_p2();
    void thread_tmp_34_fu_428_p1();
    void thread_tmp_35_fu_504_p1();
    void thread_tmp_36_fu_615_p3();
    void thread_tmp_39_fu_701_p1();
    void thread_tmp_3_fu_432_p3();
    void thread_tmp_40_fu_724_p3();
    void thread_tmp_41_fu_737_p1();
    void thread_tmp_4_fu_677_p2();
    void thread_tmp_51_cast_fu_715_p1();
    void thread_tmp_5_fu_683_p2();
    void thread_tmp_6_fu_696_p2();
    void thread_tmp_7_fu_704_p2();
    void thread_tmp_8_fu_710_p2();
    void thread_tmp_fu_280_p3();
    void thread_tmp_s_fu_655_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
