// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sin_or_cos_double_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sin_or_cos_double_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sin_or_cos_double_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state1 = "1";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state2 = "10";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state3 = "100";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state4 = "1000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state5 = "10000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state6 = "100000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_1 = "1";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_2 = "10";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3 = "11";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_4 = "100";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_8 = "1000";
const sc_lv<1> sin_or_cos_double_s::ap_const_lv1_0 = "0";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_9 = "1001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A = "1010";
const sc_lv<1> sin_or_cos_double_s::ap_const_lv1_1 = "1";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_B = "1011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_C = "1100";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_D = "1101";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_F = "1111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_10 = "10000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_11 = "10001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_12 = "10010";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_15 = "10101";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_16 = "10110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_17 = "10111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_18 = "11000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_19 = "11001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_1A = "11010";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_1E = "11110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_1F = "11111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3F = "111111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_34 = "110100";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3E = "111110";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_3FE = "1111111110";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_44D = "10001001101";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_4A = "1001010";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_7 = "111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_56 = "1010110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_FF = "11111111";
const sc_lv<52> sin_or_cos_double_s::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_2B = "101011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A6 = "10100110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A7 = "10100111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_A9 = "10101001";
const sc_lv<3> sin_or_cos_double_s::ap_const_lv3_0 = "000";
const sc_lv<124> sin_or_cos_double_s::ap_const_lv124_0 = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_403 = "10000000011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_7B = "1111011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3D = "111101";
const sc_lv<2> sin_or_cos_double_s::ap_const_lv2_3 = "11";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_0 = "00000000000";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_7FF = "11111111111";
const sc_lv<12> sin_or_cos_double_s::ap_const_lv12_0 = "000000000000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_38 = "111000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_37 = "110111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_31 = "110001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_61 = "1100001";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_6B = "1101011";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_2D = "101101";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_5C = "1011100";
const sc_lv<4> sin_or_cos_double_s::ap_const_lv4_0 = "0000";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_26 = "100110";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_4A = "1001010";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_3B = "111011";
const sc_lv<63> sin_or_cos_double_s::ap_const_lv63_7FFFFFFFFFFFFFFF = "111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> sin_or_cos_double_s::ap_const_lv32_7D = "1111101";
const sc_lv<11> sin_or_cos_double_s::ap_const_lv11_3FF = "1111111111";
const sc_lv<52> sin_or_cos_double_s::ap_const_lv52_FFFFFFFFFFFFF = "1111111111111111111111111111111111111111111111111111";
const sc_lv<64> sin_or_cos_double_s::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const bool sin_or_cos_double_s::ap_const_boolean_1 = true;

sin_or_cos_double_s::sin_or_cos_double_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    hls_ref_4oPi_table_s_U = new sin_or_cos_doublecud("hls_ref_4oPi_table_s_U");
    hls_ref_4oPi_table_s_U->clk(ap_clk);
    hls_ref_4oPi_table_s_U->reset(ap_rst);
    hls_ref_4oPi_table_s_U->address0(hls_ref_4oPi_table_s_address0);
    hls_ref_4oPi_table_s_U->ce0(hls_ref_4oPi_table_s_ce0);
    hls_ref_4oPi_table_s_U->q0(hls_ref_4oPi_table_s_q0);
    hls_hotbm_fourth_o_19_U = new sin_or_cos_doubledEe("hls_hotbm_fourth_o_19_U");
    hls_hotbm_fourth_o_19_U->clk(ap_clk);
    hls_hotbm_fourth_o_19_U->reset(ap_rst);
    hls_hotbm_fourth_o_19_U->address0(hls_hotbm_fourth_o_19_address0);
    hls_hotbm_fourth_o_19_U->ce0(hls_hotbm_fourth_o_19_ce0);
    hls_hotbm_fourth_o_19_U->q0(hls_hotbm_fourth_o_19_q0);
    hls_hotbm_fourth_o_20_U = new sin_or_cos_doubleeOg("hls_hotbm_fourth_o_20_U");
    hls_hotbm_fourth_o_20_U->clk(ap_clk);
    hls_hotbm_fourth_o_20_U->reset(ap_rst);
    hls_hotbm_fourth_o_20_U->address0(hls_hotbm_fourth_o_20_address0);
    hls_hotbm_fourth_o_20_U->ce0(hls_hotbm_fourth_o_20_ce0);
    hls_hotbm_fourth_o_20_U->q0(hls_hotbm_fourth_o_20_q0);
    hls_hotbm_fourth_o_21_U = new sin_or_cos_doublefYi("hls_hotbm_fourth_o_21_U");
    hls_hotbm_fourth_o_21_U->clk(ap_clk);
    hls_hotbm_fourth_o_21_U->reset(ap_rst);
    hls_hotbm_fourth_o_21_U->address0(hls_hotbm_fourth_o_21_address0);
    hls_hotbm_fourth_o_21_U->ce0(hls_hotbm_fourth_o_21_ce0);
    hls_hotbm_fourth_o_21_U->q0(hls_hotbm_fourth_o_21_q0);
    hls_hotbm_fourth_o_27_U = new sin_or_cos_doubleg8j("hls_hotbm_fourth_o_27_U");
    hls_hotbm_fourth_o_27_U->clk(ap_clk);
    hls_hotbm_fourth_o_27_U->reset(ap_rst);
    hls_hotbm_fourth_o_27_U->address0(hls_hotbm_fourth_o_27_address0);
    hls_hotbm_fourth_o_27_U->ce0(hls_hotbm_fourth_o_27_ce0);
    hls_hotbm_fourth_o_27_U->q0(hls_hotbm_fourth_o_27_q0);
    hls_hotbm_fourth_o_U = new sin_or_cos_doublehbi("hls_hotbm_fourth_o_U");
    hls_hotbm_fourth_o_U->clk(ap_clk);
    hls_hotbm_fourth_o_U->reset(ap_rst);
    hls_hotbm_fourth_o_U->address0(hls_hotbm_fourth_o_address0);
    hls_hotbm_fourth_o_U->ce0(hls_hotbm_fourth_o_ce0);
    hls_hotbm_fourth_o_U->q0(hls_hotbm_fourth_o_q0);
    grp_scaled_fixed2ieee_fu_260 = new scaled_fixed2ieee("grp_scaled_fixed2ieee_fu_260");
    grp_scaled_fixed2ieee_fu_260->ap_clk(ap_clk);
    grp_scaled_fixed2ieee_fu_260->ap_rst(ap_rst);
    grp_scaled_fixed2ieee_fu_260->ap_start(grp_scaled_fixed2ieee_fu_260_ap_start);
    grp_scaled_fixed2ieee_fu_260->ap_done(grp_scaled_fixed2ieee_fu_260_ap_done);
    grp_scaled_fixed2ieee_fu_260->ap_idle(grp_scaled_fixed2ieee_fu_260_ap_idle);
    grp_scaled_fixed2ieee_fu_260->ap_ready(grp_scaled_fixed2ieee_fu_260_ap_ready);
    grp_scaled_fixed2ieee_fu_260->in_V(result_V_reg_1447);
    grp_scaled_fixed2ieee_fu_260->prescale(tmp_54_cast_reg_1452);
    grp_scaled_fixed2ieee_fu_260->ap_return(grp_scaled_fixed2ieee_fu_260_ap_return);
    houghTransform_muibs_U4 = new houghTransform_muibs<1,5,170,53,223>("houghTransform_muibs_U4");
    houghTransform_muibs_U4->clk(ap_clk);
    houghTransform_muibs_U4->reset(ap_rst);
    houghTransform_muibs_U4->din0(grp_fu_361_p0);
    houghTransform_muibs_U4->din1(grp_fu_361_p1);
    houghTransform_muibs_U4->ce(ap_var_for_const0);
    houghTransform_muibs_U4->dout(grp_fu_361_p2);
    houghTransform_mujbC_U5 = new houghTransform_mujbC<1,5,49,49,98>("houghTransform_mujbC_U5");
    houghTransform_mujbC_U5->clk(ap_clk);
    houghTransform_mujbC_U5->reset(ap_rst);
    houghTransform_mujbC_U5->din0(grp_fu_585_p0);
    houghTransform_mujbC_U5->din1(grp_fu_585_p1);
    houghTransform_mujbC_U5->ce(ap_var_for_const0);
    houghTransform_mujbC_U5->dout(grp_fu_585_p2);
    houghTransform_mukbM_U6 = new houghTransform_mukbM<1,1,1,1,1,1,1,1,1,1,3,1>("houghTransform_mukbM_U6");
    houghTransform_mukbM_U6->din1(ap_var_for_const1);
    houghTransform_mukbM_U6->din2(ap_var_for_const2);
    houghTransform_mukbM_U6->din3(ap_var_for_const2);
    houghTransform_mukbM_U6->din4(ap_var_for_const1);
    houghTransform_mukbM_U6->din5(ap_var_for_const1);
    houghTransform_mukbM_U6->din6(ap_var_for_const2);
    houghTransform_mukbM_U6->din7(ap_var_for_const2);
    houghTransform_mukbM_U6->din8(ap_var_for_const1);
    houghTransform_mukbM_U6->din9(p_Val2_29_reg_1168);
    houghTransform_mukbM_U6->dout(tmp_fu_591_p10);
    houghTransform_mujbC_U7 = new houghTransform_mujbC<1,5,49,49,98>("houghTransform_mujbC_U7");
    houghTransform_mujbC_U7->clk(ap_clk);
    houghTransform_mujbC_U7->reset(ap_rst);
    houghTransform_mujbC_U7->din0(grp_fu_648_p0);
    houghTransform_mujbC_U7->din1(grp_fu_648_p1);
    houghTransform_mujbC_U7->ce(ap_var_for_const0);
    houghTransform_mujbC_U7->dout(grp_fu_648_p2);
    houghTransform_mujbC_U8 = new houghTransform_mujbC<1,5,49,49,98>("houghTransform_mujbC_U8");
    houghTransform_mujbC_U8->clk(ap_clk);
    houghTransform_mujbC_U8->reset(ap_rst);
    houghTransform_mujbC_U8->din0(grp_fu_653_p0);
    houghTransform_mujbC_U8->din1(grp_fu_653_p1);
    houghTransform_mujbC_U8->ce(ap_var_for_const0);
    houghTransform_mujbC_U8->dout(grp_fu_653_p2);
    houghTransform_mulbW_U9 = new houghTransform_mulbW<1,5,56,52,108>("houghTransform_mulbW_U9");
    houghTransform_mulbW_U9->clk(ap_clk);
    houghTransform_mulbW_U9->reset(ap_rst);
    houghTransform_mulbW_U9->din0(grp_fu_665_p0);
    houghTransform_mulbW_U9->din1(hls_hotbm_fourth_o_29_reg_1299);
    houghTransform_mulbW_U9->ce(ap_var_for_const0);
    houghTransform_mulbW_U9->dout(grp_fu_665_p2);
    houghTransform_mumb6_U10 = new houghTransform_mumb6<1,5,49,44,93>("houghTransform_mumb6_U10");
    houghTransform_mumb6_U10->clk(ap_clk);
    houghTransform_mumb6_U10->reset(ap_rst);
    houghTransform_mumb6_U10->din0(grp_fu_677_p0);
    houghTransform_mumb6_U10->din1(hls_hotbm_fourth_o_31_reg_1304);
    houghTransform_mumb6_U10->ce(ap_var_for_const0);
    houghTransform_mumb6_U10->dout(grp_fu_677_p2);
    houghTransform_muncg_U11 = new houghTransform_muncg<1,2,42,33,75>("houghTransform_muncg_U11");
    houghTransform_muncg_U11->clk(ap_clk);
    houghTransform_muncg_U11->reset(ap_rst);
    houghTransform_muncg_U11->din0(grp_fu_736_p0);
    houghTransform_muncg_U11->din1(grp_fu_736_p1);
    houghTransform_muncg_U11->ce(ap_var_for_const0);
    houghTransform_muncg_U11->dout(grp_fu_736_p2);
    houghTransform_muocq_U12 = new houghTransform_muocq<1,2,35,25,60>("houghTransform_muocq_U12");
    houghTransform_muocq_U12->clk(ap_clk);
    houghTransform_muocq_U12->reset(ap_rst);
    houghTransform_muocq_U12->din0(grp_fu_748_p0);
    houghTransform_muocq_U12->din1(grp_fu_748_p1);
    houghTransform_muocq_U12->ce(ap_var_for_const0);
    houghTransform_muocq_U12->dout(grp_fu_748_p2);
    houghTransform_mupcA_U13 = new houghTransform_mupcA<1,5,64,63,126>("houghTransform_mupcA_U13");
    houghTransform_mupcA_U13->clk(ap_clk);
    houghTransform_mupcA_U13->reset(ap_rst);
    houghTransform_mupcA_U13->din0(r_V_3_reg_1432);
    houghTransform_mupcA_U13->din1(grp_fu_837_p1);
    houghTransform_mupcA_U13->ce(ap_var_for_const0);
    houghTransform_mupcA_U13->dout(grp_fu_837_p2);
    houghTransform_muqcK_U14 = new houghTransform_muqcK<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("houghTransform_muqcK_U14");
    houghTransform_muqcK_U14->din1(ap_var_for_const1);
    houghTransform_muqcK_U14->din2(ap_var_for_const1);
    houghTransform_muqcK_U14->din3(ap_var_for_const1);
    houghTransform_muqcK_U14->din4(ap_var_for_const2);
    houghTransform_muqcK_U14->din5(ap_var_for_const2);
    houghTransform_muqcK_U14->din6(ap_var_for_const2);
    houghTransform_muqcK_U14->din7(ap_var_for_const2);
    houghTransform_muqcK_U14->din8(ap_var_for_const1);
    houghTransform_muqcK_U14->din9(ap_var_for_const1);
    houghTransform_muqcK_U14->din10(ap_var_for_const2);
    houghTransform_muqcK_U14->din11(ap_var_for_const2);
    houghTransform_muqcK_U14->din12(ap_var_for_const2);
    houghTransform_muqcK_U14->din13(ap_var_for_const2);
    houghTransform_muqcK_U14->din14(ap_var_for_const1);
    houghTransform_muqcK_U14->din15(ap_var_for_const1);
    houghTransform_muqcK_U14->din16(ap_var_for_const1);
    houghTransform_muqcK_U14->din17(p_Result_26_fu_901_p3);
    houghTransform_muqcK_U14->dout(tmp_3_fu_907_p18);
    houghTransform_muqcK_U15 = new houghTransform_muqcK<1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,1>("houghTransform_muqcK_U15");
    houghTransform_muqcK_U15->din1(ap_var_for_const1);
    houghTransform_muqcK_U15->din2(ap_var_for_const1);
    houghTransform_muqcK_U15->din3(ap_var_for_const2);
    houghTransform_muqcK_U15->din4(ap_var_for_const1);
    houghTransform_muqcK_U15->din5(ap_var_for_const2);
    houghTransform_muqcK_U15->din6(ap_var_for_const2);
    houghTransform_muqcK_U15->din7(ap_var_for_const1);
    houghTransform_muqcK_U15->din8(ap_var_for_const2);
    houghTransform_muqcK_U15->din9(ap_var_for_const2);
    houghTransform_muqcK_U15->din10(ap_var_for_const1);
    houghTransform_muqcK_U15->din11(ap_var_for_const2);
    houghTransform_muqcK_U15->din12(ap_var_for_const2);
    houghTransform_muqcK_U15->din13(ap_var_for_const1);
    houghTransform_muqcK_U15->din14(ap_var_for_const2);
    houghTransform_muqcK_U15->din15(ap_var_for_const1);
    houghTransform_muqcK_U15->din16(ap_var_for_const1);
    houghTransform_muqcK_U15->din17(p_Result_26_fu_901_p3);
    houghTransform_muqcK_U15->dout(tmp_4_fu_945_p18);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Ex_V_fu_502_p2);
    sensitive << ( storemerge_i_fu_475_p3 );
    sensitive << ( tmp_68_i_fu_499_p1 );

    SC_METHOD(thread_Mx_V_read_assign_fu_807_p3);
    sensitive << ( Mx_V_reg_1213 );
    sensitive << ( cos_basis_fu_801_p3 );

    SC_METHOD(thread_Mx_zeros_V_fu_461_p1);
    sensitive << ( tmp_i4_i_fu_453_p3 );

    SC_METHOD(thread_OP1_V_fu_582_p1);
    sensitive << ( tmp_i1_reg_1245 );

    SC_METHOD(thread_OP2_V_fu_645_p1);
    sensitive << ( tmp_94_i_reg_1293 );

    SC_METHOD(thread_addr_V_fu_304_p3);
    sensitive << ( closepath_reg_1109 );
    sensitive << ( expv_op_reg_1116 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_scaled_fixed2ieee_fu_260_ap_done );
    sensitive << ( ap_CS_fsm_state32 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_scaled_fixed2ieee_fu_260_ap_done );
    sensitive << ( ap_CS_fsm_state32 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_scaled_fixed2ieee_fu_260_ap_done );
    sensitive << ( ap_CS_fsm_state32 );
    sensitive << ( ret_i_i_fu_1086_p1 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_closepath_fu_292_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( loc_V_fu_278_p4 );

    SC_METHOD(thread_cos_basis_fu_801_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_cos_basis_fu_801_p3);
    sensitive << ( tmp_reg_1263 );
    sensitive << ( cos_basis_fu_801_p0 );
    sensitive << ( tmp_s_fu_796_p2 );

    SC_METHOD(thread_expv_op_fu_298_p2);
    sensitive << ( loc_V_fu_278_p4 );

    SC_METHOD(thread_grp_fu_361_p0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_fu_361_p00 );

    SC_METHOD(thread_grp_fu_361_p00);
    sensitive << ( ret_V_reg_1136 );

    SC_METHOD(thread_grp_fu_361_p1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_fu_361_p10 );

    SC_METHOD(thread_grp_fu_361_p10);
    sensitive << ( p_Result_20_fu_347_p3 );

    SC_METHOD(thread_grp_fu_585_p0);
    sensitive << ( OP1_V_fu_582_p1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fu_585_p1);
    sensitive << ( OP1_V_fu_582_p1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_fu_648_p0);
    sensitive << ( OP2_V_fu_645_p1 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_grp_fu_648_p1);
    sensitive << ( OP1_V_reg_1250 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_grp_fu_653_p0);
    sensitive << ( OP2_V_fu_645_p1 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_grp_fu_653_p1);
    sensitive << ( OP2_V_fu_645_p1 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_grp_fu_665_p0);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( grp_fu_665_p00 );

    SC_METHOD(thread_grp_fu_665_p00);
    sensitive << ( p_Val2_15_reg_1240 );

    SC_METHOD(thread_grp_fu_677_p0);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( grp_fu_677_p00 );

    SC_METHOD(thread_grp_fu_677_p00);
    sensitive << ( tmp_94_i_reg_1293 );

    SC_METHOD(thread_grp_fu_736_p0);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( grp_fu_736_p00 );

    SC_METHOD(thread_grp_fu_736_p00);
    sensitive << ( tmp_96_i_reg_1351 );

    SC_METHOD(thread_grp_fu_736_p1);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( grp_fu_736_p10 );

    SC_METHOD(thread_grp_fu_736_p10);
    sensitive << ( hls_hotbm_fourth_o_33_reg_1376 );

    SC_METHOD(thread_grp_fu_748_p0);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( grp_fu_748_p00 );

    SC_METHOD(thread_grp_fu_748_p00);
    sensitive << ( tmp_98_i_reg_1356 );

    SC_METHOD(thread_grp_fu_748_p1);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( grp_fu_748_p10 );

    SC_METHOD(thread_grp_fu_748_p10);
    sensitive << ( hls_hotbm_fourth_o_35_reg_1381 );

    SC_METHOD(thread_grp_fu_837_p1);
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( grp_fu_837_p10 );

    SC_METHOD(thread_grp_fu_837_p10);
    sensitive << ( Mx_V_read_assign_reg_1427 );

    SC_METHOD(thread_grp_scaled_fixed2ieee_fu_260_ap_start);
    sensitive << ( ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start );

    SC_METHOD(thread_hls_hotbm_fourth_o_19_address0);
    sensitive << ( tmp_99_i_reg_1276 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_hls_hotbm_fourth_o_19_ce0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_hls_hotbm_fourth_o_20_address0);
    sensitive << ( tmp_99_i_fu_629_p1 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_hls_hotbm_fourth_o_20_ce0);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_hls_hotbm_fourth_o_21_address0);
    sensitive << ( tmp_99_i_fu_629_p1 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_hls_hotbm_fourth_o_21_ce0);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_hls_hotbm_fourth_o_27_address0);
    sensitive << ( tmp_99_i_reg_1276 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_hls_hotbm_fourth_o_27_ce0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_hls_hotbm_fourth_o_address0);
    sensitive << ( tmp_99_i_reg_1276 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_hls_hotbm_fourth_o_ce0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_hls_ref_4oPi_table_s_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i2_i_fu_320_p1 );

    SC_METHOD(thread_hls_ref_4oPi_table_s_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_isNeg_fu_512_p3);
    sensitive << ( Ex_V_fu_502_p2 );

    SC_METHOD(thread_loc_V_1_fu_288_p1);
    sensitive << ( p_Val2_s_fu_266_p1 );

    SC_METHOD(thread_loc_V_2_fu_887_p4);
    sensitive << ( p_Val2_25_fu_875_p1 );

    SC_METHOD(thread_loc_V_3_fu_897_p1);
    sensitive << ( p_Val2_25_fu_875_p1 );

    SC_METHOD(thread_loc_V_fu_278_p4);
    sensitive << ( p_Val2_s_fu_266_p1 );

    SC_METHOD(thread_not_do_cos_i_fu_612_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_not_do_cos_i_fu_612_p2);
    sensitive << ( not_do_cos_i_fu_612_p0 );

    SC_METHOD(thread_not_or_cond_demorgan_fu_1045_p2);
    sensitive << ( tmp_7_reg_1151 );
    sensitive << ( tmp_6_reg_1200 );

    SC_METHOD(thread_not_or_cond_fu_1049_p2);
    sensitive << ( not_or_cond_demorgan_fu_1045_p2 );

    SC_METHOD(thread_not_tmp_s_fu_1011_p2);
    sensitive << ( tmp_8_reg_1206 );

    SC_METHOD(thread_or_cond_fu_996_p2);
    sensitive << ( tmp_7_reg_1151 );
    sensitive << ( tmp_6_reg_1200 );

    SC_METHOD(thread_p_Ex_V_ret_fu_843_p3);
    sensitive << ( Ex_V_reg_1220 );
    sensitive << ( cos_basis_reg_1421 );

    SC_METHOD(thread_p_Result_1_fu_1000_p2);
    sensitive << ( p_Result_19_reg_1090 );
    sensitive << ( not_do_cos_i_reg_1270 );

    SC_METHOD(thread_p_Result_20_fu_347_p3);
    sensitive << ( loc_V_1_reg_1103 );

    SC_METHOD(thread_p_Result_21_fu_427_p3);
    sensitive << ( p_Result_i3_i_fu_417_p4 );

    SC_METHOD(thread_p_Result_22_fu_435_p4);
    sensitive << ( p_Result_21_fu_427_p3 );

    SC_METHOD(thread_p_Result_23_fu_445_p3);
    sensitive << ( p_Result_22_fu_435_p4 );

    SC_METHOD(thread_p_Result_24_fu_622_p3);
    sensitive << ( p_Result_i_reg_1235 );
    sensitive << ( sin_basis_fu_618_p2 );

    SC_METHOD(thread_p_Result_25_fu_879_p3);
    sensitive << ( p_Val2_25_fu_875_p1 );

    SC_METHOD(thread_p_Result_26_fu_901_p3);
    sensitive << ( p_Result_19_reg_1090 );
    sensitive << ( p_Val2_29_reg_1168 );

    SC_METHOD(thread_p_Result_27_fu_1076_p4);
    sensitive << ( p_Result_s_56_fu_1029_p3 );
    sensitive << ( ret_V_6_fu_1037_p3 );
    sensitive << ( ret_V_7_fu_1068_p3 );

    SC_METHOD(thread_p_Result_2_fu_1022_p3);
    sensitive << ( tmp_8_reg_1206 );
    sensitive << ( loc_V_2_fu_887_p4 );

    SC_METHOD(thread_p_Result_3_cast_fu_1055_p3);
    sensitive << ( not_or_cond_fu_1049_p2 );

    SC_METHOD(thread_p_Result_i3_i_fu_417_p4);
    sensitive << ( p_Val2_11_fu_412_p3 );

    SC_METHOD(thread_p_Result_i_i_fu_310_p4);
    sensitive << ( addr_V_fu_304_p3 );

    SC_METHOD(thread_p_Result_s_55_fu_1016_p2);
    sensitive << ( p_Result_s_fu_990_p2 );
    sensitive << ( not_tmp_s_fu_1011_p2 );

    SC_METHOD(thread_p_Result_s_56_fu_1029_p3);
    sensitive << ( or_cond_fu_996_p2 );
    sensitive << ( p_Result_1_fu_1000_p2 );
    sensitive << ( p_Result_s_55_fu_1016_p2 );

    SC_METHOD(thread_p_Result_s_fu_990_p2);
    sensitive << ( tmp_5_fu_983_p3 );
    sensitive << ( p_Result_25_fu_879_p3 );

    SC_METHOD(thread_p_Val2_11_fu_412_p3);
    sensitive << ( p_Val2_9_reg_1157 );
    sensitive << ( tmp_13_reg_1174 );
    sensitive << ( p_Val2_i_reg_1179 );

    SC_METHOD(thread_p_Val2_13_fu_484_p2);
    sensitive << ( p_Val2_11_reg_1189 );
    sensitive << ( tmp_65_i_fu_481_p1 );

    SC_METHOD(thread_p_Val2_14_fu_551_p3);
    sensitive << ( isNeg_reg_1225 );
    sensitive << ( tmp_72_i_fu_541_p2 );
    sensitive << ( tmp_73_i_fu_546_p2 );

    SC_METHOD(thread_p_Val2_15_fu_568_p1);
    sensitive << ( p_Val2_14_fu_551_p3 );

    SC_METHOD(thread_p_Val2_20_fu_723_p3);
    sensitive << ( p_Val2_19_reg_1361 );

    SC_METHOD(thread_p_Val2_21_fu_761_p2);
    sensitive << ( tmp_101_i_fu_754_p1 );
    sensitive << ( tmp_102_i_fu_758_p1 );

    SC_METHOD(thread_p_Val2_22_fu_770_p2);
    sensitive << ( p_Val2_21_fu_761_p2 );
    sensitive << ( tmp_104_i_cast_fu_767_p1 );

    SC_METHOD(thread_p_Val2_23_fu_817_p2);
    sensitive << ( p_Val2_22_reg_1406 );
    sensitive << ( tmp_106_i_cast_fu_814_p1 );

    SC_METHOD(thread_p_Val2_25_fu_875_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_260_ap_return );

    SC_METHOD(thread_p_Val2_29_fu_392_p3);
    sensitive << ( closepath_reg_1109 );
    sensitive << ( tmp_64_i_reg_1163 );

    SC_METHOD(thread_p_Val2_i_fu_402_p2);
    sensitive << ( p_Val2_9_reg_1157 );

    SC_METHOD(thread_p_Val2_s_fu_266_p1);
    sensitive << ( t_in );

    SC_METHOD(thread_p_cast_cast_fu_1004_p0);
    sensitive << ( do_cos );
    sensitive << ( ap_CS_fsm_state32 );

    SC_METHOD(thread_p_cast_cast_fu_1004_p3);
    sensitive << ( p_cast_cast_fu_1004_p0 );

    SC_METHOD(thread_r_V_3_fu_825_p2);
    sensitive << ( p_Val2_23_fu_817_p2 );
    sensitive << ( tmp_108_i_cast_fu_822_p1 );

    SC_METHOD(thread_r_V_4_fu_332_p2);
    sensitive << ( table_256_V_reg_1131 );
    sensitive << ( tmp_52_i_i_fu_329_p1 );

    SC_METHOD(thread_r_V_fu_864_p2);
    sensitive << ( rhs_V_fu_860_p1 );

    SC_METHOD(thread_ret_V_6_fu_1037_p3);
    sensitive << ( or_cond_fu_996_p2 );
    sensitive << ( p_cast_cast_fu_1004_p3 );
    sensitive << ( p_Result_2_fu_1022_p3 );

    SC_METHOD(thread_ret_V_7_fu_1068_p3);
    sensitive << ( tmp_9_fu_1063_p2 );
    sensitive << ( p_Result_3_cast_fu_1055_p3 );
    sensitive << ( loc_V_3_fu_897_p1 );

    SC_METHOD(thread_ret_i_i_fu_1086_p1);
    sensitive << ( p_Result_27_fu_1076_p4 );

    SC_METHOD(thread_rhs_V_fu_860_p1);
    sensitive << ( p_Ex_V_ret_fu_843_p3 );

    SC_METHOD(thread_sh_assign_4_cast_fu_534_p1);
    sensitive << ( sh_assign_reg_1230 );

    SC_METHOD(thread_sh_assign_fu_526_p3);
    sensitive << ( isNeg_fu_512_p3 );
    sensitive << ( sh_cast_fu_508_p1 );
    sensitive << ( tmp_70_i_fu_520_p2 );

    SC_METHOD(thread_sh_cast_fu_508_p1);
    sensitive << ( Ex_V_fu_502_p2 );

    SC_METHOD(thread_sin_basis_fu_618_p2);
    sensitive << ( tmp_reg_1263 );
    sensitive << ( not_do_cos_i_reg_1270 );

    SC_METHOD(thread_storemerge_i_fu_475_p3);
    sensitive << ( closepath_reg_1109 );
    sensitive << ( tmp_i_reg_1184 );

    SC_METHOD(thread_tmp_101_i_fu_754_p1);
    sensitive << ( p_Val2_20_fu_723_p3 );

    SC_METHOD(thread_tmp_102_i_fu_758_p1);
    sensitive << ( tmp_23_i_reg_1366 );

    SC_METHOD(thread_tmp_104_i_cast_fu_767_p1);
    sensitive << ( tmp_25_i_reg_1371 );

    SC_METHOD(thread_tmp_106_i_cast_fu_814_p1);
    sensitive << ( tmp_1_reg_1411 );

    SC_METHOD(thread_tmp_108_i_cast_fu_822_p1);
    sensitive << ( tmp_2_reg_1416 );

    SC_METHOD(thread_tmp_12_fu_325_p1);
    sensitive << ( addr_V_fu_304_p3 );

    SC_METHOD(thread_tmp_13_fu_398_p1);
    sensitive << ( p_Val2_29_fu_392_p3 );

    SC_METHOD(thread_tmp_52_i_i_fu_329_p1);
    sensitive << ( tmp_12_reg_1126 );

    SC_METHOD(thread_tmp_54_cast_fu_870_p1);
    sensitive << ( r_V_fu_864_p2 );

    SC_METHOD(thread_tmp_5_fu_983_p3);
    sensitive << ( cos_basis_reg_1421 );
    sensitive << ( tmp_3_fu_907_p18 );
    sensitive << ( tmp_4_fu_945_p18 );

    SC_METHOD(thread_tmp_65_i_fu_481_p1);
    sensitive << ( Mx_zeros_V_reg_1194 );

    SC_METHOD(thread_tmp_68_i_fu_499_p1);
    sensitive << ( Mx_zeros_V_reg_1194 );

    SC_METHOD(thread_tmp_6_fu_465_p2);
    sensitive << ( loc_V_reg_1096 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_tmp_70_i_fu_520_p2);
    sensitive << ( sh_cast_fu_508_p1 );

    SC_METHOD(thread_tmp_71_i_fu_537_p1);
    sensitive << ( sh_assign_4_cast_fu_534_p1 );

    SC_METHOD(thread_tmp_72_i_fu_541_p2);
    sensitive << ( Mx_V_reg_1213 );
    sensitive << ( tmp_71_i_fu_537_p1 );

    SC_METHOD(thread_tmp_73_i_fu_546_p2);
    sensitive << ( Mx_V_reg_1213 );
    sensitive << ( tmp_71_i_fu_537_p1 );

    SC_METHOD(thread_tmp_7_fu_367_p2);
    sensitive << ( loc_V_1_reg_1103 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_tmp_8_fu_470_p2);
    sensitive << ( loc_V_reg_1096 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_tmp_99_i_fu_629_p1);
    sensitive << ( p_Result_24_fu_622_p3 );

    SC_METHOD(thread_tmp_9_fu_1063_p2);
    sensitive << ( tmp_8_reg_1206 );
    sensitive << ( or_cond_fu_996_p2 );

    SC_METHOD(thread_tmp_i2_i_fu_320_p1);
    sensitive << ( p_Result_i_i_fu_310_p4 );

    SC_METHOD(thread_tmp_i4_i_fu_453_p3);
    sensitive << ( p_Result_23_fu_445_p3 );

    SC_METHOD(thread_tmp_i_fu_407_p2);
    sensitive << ( loc_V_reg_1096 );

    SC_METHOD(thread_tmp_s_fu_796_p2);
    sensitive << ( tmp_reg_1263 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_scaled_fixed2ieee_fu_260_ap_done );
    sensitive << ( ap_CS_fsm_state32 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "00000000000000000000000000000001";
    ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start = SC_LOGIC_0;
    ap_return_preg = "0000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sin_or_cos_double_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, t_in, "(port)t_in");
    sc_trace(mVcdFile, do_cos, "(port)do_cos");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, hls_ref_4oPi_table_s_address0, "hls_ref_4oPi_table_s_address0");
    sc_trace(mVcdFile, hls_ref_4oPi_table_s_ce0, "hls_ref_4oPi_table_s_ce0");
    sc_trace(mVcdFile, hls_ref_4oPi_table_s_q0, "hls_ref_4oPi_table_s_q0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_19_address0, "hls_hotbm_fourth_o_19_address0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_19_ce0, "hls_hotbm_fourth_o_19_ce0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_19_q0, "hls_hotbm_fourth_o_19_q0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_20_address0, "hls_hotbm_fourth_o_20_address0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_20_ce0, "hls_hotbm_fourth_o_20_ce0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_20_q0, "hls_hotbm_fourth_o_20_q0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_21_address0, "hls_hotbm_fourth_o_21_address0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_21_ce0, "hls_hotbm_fourth_o_21_ce0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_21_q0, "hls_hotbm_fourth_o_21_q0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_27_address0, "hls_hotbm_fourth_o_27_address0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_27_ce0, "hls_hotbm_fourth_o_27_ce0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_27_q0, "hls_hotbm_fourth_o_27_q0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_address0, "hls_hotbm_fourth_o_address0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_ce0, "hls_hotbm_fourth_o_ce0");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_q0, "hls_hotbm_fourth_o_q0");
    sc_trace(mVcdFile, p_Result_19_reg_1090, "p_Result_19_reg_1090");
    sc_trace(mVcdFile, loc_V_fu_278_p4, "loc_V_fu_278_p4");
    sc_trace(mVcdFile, loc_V_reg_1096, "loc_V_reg_1096");
    sc_trace(mVcdFile, loc_V_1_fu_288_p1, "loc_V_1_fu_288_p1");
    sc_trace(mVcdFile, loc_V_1_reg_1103, "loc_V_1_reg_1103");
    sc_trace(mVcdFile, closepath_fu_292_p2, "closepath_fu_292_p2");
    sc_trace(mVcdFile, closepath_reg_1109, "closepath_reg_1109");
    sc_trace(mVcdFile, expv_op_fu_298_p2, "expv_op_fu_298_p2");
    sc_trace(mVcdFile, expv_op_reg_1116, "expv_op_reg_1116");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_12_fu_325_p1, "tmp_12_fu_325_p1");
    sc_trace(mVcdFile, tmp_12_reg_1126, "tmp_12_reg_1126");
    sc_trace(mVcdFile, table_256_V_reg_1131, "table_256_V_reg_1131");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ret_V_reg_1136, "ret_V_reg_1136");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_7_fu_367_p2, "tmp_7_fu_367_p2");
    sc_trace(mVcdFile, tmp_7_reg_1151, "tmp_7_reg_1151");
    sc_trace(mVcdFile, p_Val2_9_reg_1157, "p_Val2_9_reg_1157");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_64_i_reg_1163, "tmp_64_i_reg_1163");
    sc_trace(mVcdFile, p_Val2_29_fu_392_p3, "p_Val2_29_fu_392_p3");
    sc_trace(mVcdFile, p_Val2_29_reg_1168, "p_Val2_29_reg_1168");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_13_fu_398_p1, "tmp_13_fu_398_p1");
    sc_trace(mVcdFile, tmp_13_reg_1174, "tmp_13_reg_1174");
    sc_trace(mVcdFile, p_Val2_i_fu_402_p2, "p_Val2_i_fu_402_p2");
    sc_trace(mVcdFile, p_Val2_i_reg_1179, "p_Val2_i_reg_1179");
    sc_trace(mVcdFile, tmp_i_fu_407_p2, "tmp_i_fu_407_p2");
    sc_trace(mVcdFile, tmp_i_reg_1184, "tmp_i_reg_1184");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, p_Val2_11_fu_412_p3, "p_Val2_11_fu_412_p3");
    sc_trace(mVcdFile, p_Val2_11_reg_1189, "p_Val2_11_reg_1189");
    sc_trace(mVcdFile, Mx_zeros_V_fu_461_p1, "Mx_zeros_V_fu_461_p1");
    sc_trace(mVcdFile, Mx_zeros_V_reg_1194, "Mx_zeros_V_reg_1194");
    sc_trace(mVcdFile, tmp_6_fu_465_p2, "tmp_6_fu_465_p2");
    sc_trace(mVcdFile, tmp_6_reg_1200, "tmp_6_reg_1200");
    sc_trace(mVcdFile, tmp_8_fu_470_p2, "tmp_8_fu_470_p2");
    sc_trace(mVcdFile, tmp_8_reg_1206, "tmp_8_reg_1206");
    sc_trace(mVcdFile, Mx_V_reg_1213, "Mx_V_reg_1213");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, Ex_V_fu_502_p2, "Ex_V_fu_502_p2");
    sc_trace(mVcdFile, Ex_V_reg_1220, "Ex_V_reg_1220");
    sc_trace(mVcdFile, isNeg_fu_512_p3, "isNeg_fu_512_p3");
    sc_trace(mVcdFile, isNeg_reg_1225, "isNeg_reg_1225");
    sc_trace(mVcdFile, sh_assign_fu_526_p3, "sh_assign_fu_526_p3");
    sc_trace(mVcdFile, sh_assign_reg_1230, "sh_assign_reg_1230");
    sc_trace(mVcdFile, p_Result_i_reg_1235, "p_Result_i_reg_1235");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, p_Val2_15_fu_568_p1, "p_Val2_15_fu_568_p1");
    sc_trace(mVcdFile, p_Val2_15_reg_1240, "p_Val2_15_reg_1240");
    sc_trace(mVcdFile, tmp_i1_reg_1245, "tmp_i1_reg_1245");
    sc_trace(mVcdFile, OP1_V_fu_582_p1, "OP1_V_fu_582_p1");
    sc_trace(mVcdFile, OP1_V_reg_1250, "OP1_V_reg_1250");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, tmp_fu_591_p10, "tmp_fu_591_p10");
    sc_trace(mVcdFile, tmp_reg_1263, "tmp_reg_1263");
    sc_trace(mVcdFile, not_do_cos_i_fu_612_p2, "not_do_cos_i_fu_612_p2");
    sc_trace(mVcdFile, not_do_cos_i_reg_1270, "not_do_cos_i_reg_1270");
    sc_trace(mVcdFile, tmp_99_i_fu_629_p1, "tmp_99_i_fu_629_p1");
    sc_trace(mVcdFile, tmp_99_i_reg_1276, "tmp_99_i_reg_1276");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, tmp_94_i_reg_1293, "tmp_94_i_reg_1293");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_29_reg_1299, "hls_hotbm_fourth_o_29_reg_1299");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_31_reg_1304, "hls_hotbm_fourth_o_31_reg_1304");
    sc_trace(mVcdFile, OP2_V_fu_645_p1, "OP2_V_fu_645_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, tmp_96_i_reg_1351, "tmp_96_i_reg_1351");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, tmp_98_i_reg_1356, "tmp_98_i_reg_1356");
    sc_trace(mVcdFile, p_Val2_19_reg_1361, "p_Val2_19_reg_1361");
    sc_trace(mVcdFile, tmp_23_i_reg_1366, "tmp_23_i_reg_1366");
    sc_trace(mVcdFile, tmp_25_i_reg_1371, "tmp_25_i_reg_1371");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_33_reg_1376, "hls_hotbm_fourth_o_33_reg_1376");
    sc_trace(mVcdFile, hls_hotbm_fourth_o_35_reg_1381, "hls_hotbm_fourth_o_35_reg_1381");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, p_Val2_22_fu_770_p2, "p_Val2_22_fu_770_p2");
    sc_trace(mVcdFile, p_Val2_22_reg_1406, "p_Val2_22_reg_1406");
    sc_trace(mVcdFile, tmp_1_reg_1411, "tmp_1_reg_1411");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, tmp_2_reg_1416, "tmp_2_reg_1416");
    sc_trace(mVcdFile, cos_basis_fu_801_p3, "cos_basis_fu_801_p3");
    sc_trace(mVcdFile, cos_basis_reg_1421, "cos_basis_reg_1421");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, Mx_V_read_assign_fu_807_p3, "Mx_V_read_assign_fu_807_p3");
    sc_trace(mVcdFile, Mx_V_read_assign_reg_1427, "Mx_V_read_assign_reg_1427");
    sc_trace(mVcdFile, r_V_3_fu_825_p2, "r_V_3_fu_825_p2");
    sc_trace(mVcdFile, r_V_3_reg_1432, "r_V_3_reg_1432");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, result_V_reg_1447, "result_V_reg_1447");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, tmp_54_cast_fu_870_p1, "tmp_54_cast_fu_870_p1");
    sc_trace(mVcdFile, tmp_54_cast_reg_1452, "tmp_54_cast_reg_1452");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_260_ap_start, "grp_scaled_fixed2ieee_fu_260_ap_start");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_260_ap_done, "grp_scaled_fixed2ieee_fu_260_ap_done");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_260_ap_idle, "grp_scaled_fixed2ieee_fu_260_ap_idle");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_260_ap_ready, "grp_scaled_fixed2ieee_fu_260_ap_ready");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_260_ap_return, "grp_scaled_fixed2ieee_fu_260_ap_return");
    sc_trace(mVcdFile, ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start, "ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, tmp_i2_i_fu_320_p1, "tmp_i2_i_fu_320_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_266_p1, "p_Val2_s_fu_266_p1");
    sc_trace(mVcdFile, addr_V_fu_304_p3, "addr_V_fu_304_p3");
    sc_trace(mVcdFile, p_Result_i_i_fu_310_p4, "p_Result_i_i_fu_310_p4");
    sc_trace(mVcdFile, tmp_52_i_i_fu_329_p1, "tmp_52_i_i_fu_329_p1");
    sc_trace(mVcdFile, r_V_4_fu_332_p2, "r_V_4_fu_332_p2");
    sc_trace(mVcdFile, p_Result_20_fu_347_p3, "p_Result_20_fu_347_p3");
    sc_trace(mVcdFile, grp_fu_361_p0, "grp_fu_361_p0");
    sc_trace(mVcdFile, grp_fu_361_p1, "grp_fu_361_p1");
    sc_trace(mVcdFile, grp_fu_361_p2, "grp_fu_361_p2");
    sc_trace(mVcdFile, p_Result_i3_i_fu_417_p4, "p_Result_i3_i_fu_417_p4");
    sc_trace(mVcdFile, p_Result_21_fu_427_p3, "p_Result_21_fu_427_p3");
    sc_trace(mVcdFile, p_Result_22_fu_435_p4, "p_Result_22_fu_435_p4");
    sc_trace(mVcdFile, p_Result_23_fu_445_p3, "p_Result_23_fu_445_p3");
    sc_trace(mVcdFile, tmp_i4_i_fu_453_p3, "tmp_i4_i_fu_453_p3");
    sc_trace(mVcdFile, tmp_65_i_fu_481_p1, "tmp_65_i_fu_481_p1");
    sc_trace(mVcdFile, p_Val2_13_fu_484_p2, "p_Val2_13_fu_484_p2");
    sc_trace(mVcdFile, storemerge_i_fu_475_p3, "storemerge_i_fu_475_p3");
    sc_trace(mVcdFile, tmp_68_i_fu_499_p1, "tmp_68_i_fu_499_p1");
    sc_trace(mVcdFile, sh_cast_fu_508_p1, "sh_cast_fu_508_p1");
    sc_trace(mVcdFile, tmp_70_i_fu_520_p2, "tmp_70_i_fu_520_p2");
    sc_trace(mVcdFile, sh_assign_4_cast_fu_534_p1, "sh_assign_4_cast_fu_534_p1");
    sc_trace(mVcdFile, tmp_71_i_fu_537_p1, "tmp_71_i_fu_537_p1");
    sc_trace(mVcdFile, tmp_72_i_fu_541_p2, "tmp_72_i_fu_541_p2");
    sc_trace(mVcdFile, tmp_73_i_fu_546_p2, "tmp_73_i_fu_546_p2");
    sc_trace(mVcdFile, p_Val2_14_fu_551_p3, "p_Val2_14_fu_551_p3");
    sc_trace(mVcdFile, grp_fu_585_p0, "grp_fu_585_p0");
    sc_trace(mVcdFile, grp_fu_585_p1, "grp_fu_585_p1");
    sc_trace(mVcdFile, not_do_cos_i_fu_612_p0, "not_do_cos_i_fu_612_p0");
    sc_trace(mVcdFile, sin_basis_fu_618_p2, "sin_basis_fu_618_p2");
    sc_trace(mVcdFile, p_Result_24_fu_622_p3, "p_Result_24_fu_622_p3");
    sc_trace(mVcdFile, grp_fu_585_p2, "grp_fu_585_p2");
    sc_trace(mVcdFile, grp_fu_648_p0, "grp_fu_648_p0");
    sc_trace(mVcdFile, grp_fu_648_p1, "grp_fu_648_p1");
    sc_trace(mVcdFile, grp_fu_653_p0, "grp_fu_653_p0");
    sc_trace(mVcdFile, grp_fu_653_p1, "grp_fu_653_p1");
    sc_trace(mVcdFile, grp_fu_665_p0, "grp_fu_665_p0");
    sc_trace(mVcdFile, grp_fu_677_p0, "grp_fu_677_p0");
    sc_trace(mVcdFile, grp_fu_648_p2, "grp_fu_648_p2");
    sc_trace(mVcdFile, grp_fu_653_p2, "grp_fu_653_p2");
    sc_trace(mVcdFile, grp_fu_665_p2, "grp_fu_665_p2");
    sc_trace(mVcdFile, grp_fu_677_p2, "grp_fu_677_p2");
    sc_trace(mVcdFile, grp_fu_736_p0, "grp_fu_736_p0");
    sc_trace(mVcdFile, grp_fu_736_p1, "grp_fu_736_p1");
    sc_trace(mVcdFile, grp_fu_748_p0, "grp_fu_748_p0");
    sc_trace(mVcdFile, grp_fu_748_p1, "grp_fu_748_p1");
    sc_trace(mVcdFile, p_Val2_20_fu_723_p3, "p_Val2_20_fu_723_p3");
    sc_trace(mVcdFile, tmp_101_i_fu_754_p1, "tmp_101_i_fu_754_p1");
    sc_trace(mVcdFile, tmp_102_i_fu_758_p1, "tmp_102_i_fu_758_p1");
    sc_trace(mVcdFile, p_Val2_21_fu_761_p2, "p_Val2_21_fu_761_p2");
    sc_trace(mVcdFile, tmp_104_i_cast_fu_767_p1, "tmp_104_i_cast_fu_767_p1");
    sc_trace(mVcdFile, grp_fu_736_p2, "grp_fu_736_p2");
    sc_trace(mVcdFile, grp_fu_748_p2, "grp_fu_748_p2");
    sc_trace(mVcdFile, cos_basis_fu_801_p0, "cos_basis_fu_801_p0");
    sc_trace(mVcdFile, tmp_s_fu_796_p2, "tmp_s_fu_796_p2");
    sc_trace(mVcdFile, tmp_106_i_cast_fu_814_p1, "tmp_106_i_cast_fu_814_p1");
    sc_trace(mVcdFile, p_Val2_23_fu_817_p2, "p_Val2_23_fu_817_p2");
    sc_trace(mVcdFile, tmp_108_i_cast_fu_822_p1, "tmp_108_i_cast_fu_822_p1");
    sc_trace(mVcdFile, grp_fu_837_p1, "grp_fu_837_p1");
    sc_trace(mVcdFile, grp_fu_837_p2, "grp_fu_837_p2");
    sc_trace(mVcdFile, p_Ex_V_ret_fu_843_p3, "p_Ex_V_ret_fu_843_p3");
    sc_trace(mVcdFile, rhs_V_fu_860_p1, "rhs_V_fu_860_p1");
    sc_trace(mVcdFile, r_V_fu_864_p2, "r_V_fu_864_p2");
    sc_trace(mVcdFile, p_Val2_25_fu_875_p1, "p_Val2_25_fu_875_p1");
    sc_trace(mVcdFile, p_Result_26_fu_901_p3, "p_Result_26_fu_901_p3");
    sc_trace(mVcdFile, tmp_3_fu_907_p18, "tmp_3_fu_907_p18");
    sc_trace(mVcdFile, tmp_4_fu_945_p18, "tmp_4_fu_945_p18");
    sc_trace(mVcdFile, tmp_5_fu_983_p3, "tmp_5_fu_983_p3");
    sc_trace(mVcdFile, p_Result_25_fu_879_p3, "p_Result_25_fu_879_p3");
    sc_trace(mVcdFile, p_cast_cast_fu_1004_p0, "p_cast_cast_fu_1004_p0");
    sc_trace(mVcdFile, p_Result_s_fu_990_p2, "p_Result_s_fu_990_p2");
    sc_trace(mVcdFile, not_tmp_s_fu_1011_p2, "not_tmp_s_fu_1011_p2");
    sc_trace(mVcdFile, loc_V_2_fu_887_p4, "loc_V_2_fu_887_p4");
    sc_trace(mVcdFile, or_cond_fu_996_p2, "or_cond_fu_996_p2");
    sc_trace(mVcdFile, p_Result_1_fu_1000_p2, "p_Result_1_fu_1000_p2");
    sc_trace(mVcdFile, p_Result_s_55_fu_1016_p2, "p_Result_s_55_fu_1016_p2");
    sc_trace(mVcdFile, p_cast_cast_fu_1004_p3, "p_cast_cast_fu_1004_p3");
    sc_trace(mVcdFile, p_Result_2_fu_1022_p3, "p_Result_2_fu_1022_p3");
    sc_trace(mVcdFile, not_or_cond_demorgan_fu_1045_p2, "not_or_cond_demorgan_fu_1045_p2");
    sc_trace(mVcdFile, not_or_cond_fu_1049_p2, "not_or_cond_fu_1049_p2");
    sc_trace(mVcdFile, tmp_9_fu_1063_p2, "tmp_9_fu_1063_p2");
    sc_trace(mVcdFile, p_Result_3_cast_fu_1055_p3, "p_Result_3_cast_fu_1055_p3");
    sc_trace(mVcdFile, loc_V_3_fu_897_p1, "loc_V_3_fu_897_p1");
    sc_trace(mVcdFile, p_Result_s_56_fu_1029_p3, "p_Result_s_56_fu_1029_p3");
    sc_trace(mVcdFile, ret_V_6_fu_1037_p3, "ret_V_6_fu_1037_p3");
    sc_trace(mVcdFile, ret_V_7_fu_1068_p3, "ret_V_7_fu_1068_p3");
    sc_trace(mVcdFile, p_Result_27_fu_1076_p4, "p_Result_27_fu_1076_p4");
    sc_trace(mVcdFile, ret_i_i_fu_1086_p1, "ret_i_i_fu_1086_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_361_p00, "grp_fu_361_p00");
    sc_trace(mVcdFile, grp_fu_361_p10, "grp_fu_361_p10");
    sc_trace(mVcdFile, grp_fu_665_p00, "grp_fu_665_p00");
    sc_trace(mVcdFile, grp_fu_677_p00, "grp_fu_677_p00");
    sc_trace(mVcdFile, grp_fu_736_p00, "grp_fu_736_p00");
    sc_trace(mVcdFile, grp_fu_736_p10, "grp_fu_736_p10");
    sc_trace(mVcdFile, grp_fu_748_p00, "grp_fu_748_p00");
    sc_trace(mVcdFile, grp_fu_748_p10, "grp_fu_748_p10");
    sc_trace(mVcdFile, grp_fu_837_p10, "grp_fu_837_p10");
#endif

    }
}

sin_or_cos_double_s::~sin_or_cos_double_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete hls_ref_4oPi_table_s_U;
    delete hls_hotbm_fourth_o_19_U;
    delete hls_hotbm_fourth_o_20_U;
    delete hls_hotbm_fourth_o_21_U;
    delete hls_hotbm_fourth_o_27_U;
    delete hls_hotbm_fourth_o_U;
    delete grp_scaled_fixed2ieee_fu_260;
    delete houghTransform_muibs_U4;
    delete houghTransform_mujbC_U5;
    delete houghTransform_mukbM_U6;
    delete houghTransform_mujbC_U7;
    delete houghTransform_mujbC_U8;
    delete houghTransform_mulbW_U9;
    delete houghTransform_mumb6_U10;
    delete houghTransform_muncg_U11;
    delete houghTransform_muocq_U12;
    delete houghTransform_mupcA_U13;
    delete houghTransform_muqcK_U14;
    delete houghTransform_muqcK_U15;
}

void sin_or_cos_double_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void sin_or_cos_double_s::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void sin_or_cos_double_s::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv1_1;
}

void sin_or_cos_double_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
            ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_scaled_fixed2ieee_fu_260_ap_ready.read())) {
            ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv64_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()) && 
             esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_260_ap_done.read(), ap_const_logic_1))) {
            ap_return_preg = ret_i_i_fu_1086_p1.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        Ex_V_reg_1220 = Ex_V_fu_502_p2.read();
        Mx_V_reg_1213 = p_Val2_13_fu_484_p2.read().range(123, 61);
        isNeg_reg_1225 = Ex_V_fu_502_p2.read().range(10, 10);
        sh_assign_reg_1230 = sh_assign_fu_526_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        Mx_V_read_assign_reg_1427 = Mx_V_read_assign_fu_807_p3.read();
        cos_basis_reg_1421 = cos_basis_fu_801_p3.read();
        r_V_3_reg_1432 = r_V_3_fu_825_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        Mx_zeros_V_reg_1194 = Mx_zeros_V_fu_461_p1.read();
        p_Val2_11_reg_1189 = p_Val2_11_fu_412_p3.read();
        tmp_6_reg_1200 = tmp_6_fu_465_p2.read();
        tmp_8_reg_1206 = tmp_8_fu_470_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        OP1_V_reg_1250 = OP1_V_fu_582_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        closepath_reg_1109 = closepath_fu_292_p2.read();
        expv_op_reg_1116 = expv_op_fu_298_p2.read();
        loc_V_1_reg_1103 = loc_V_1_fu_288_p1.read();
        loc_V_reg_1096 = p_Val2_s_fu_266_p1.read().range(62, 52);
        p_Result_19_reg_1090 = p_Val2_s_fu_266_p1.read().range(63, 63);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        hls_hotbm_fourth_o_29_reg_1299 = hls_hotbm_fourth_o_20_q0.read();
        hls_hotbm_fourth_o_31_reg_1304 = hls_hotbm_fourth_o_21_q0.read();
        tmp_94_i_reg_1293 = grp_fu_585_p2.read().range(97, 49);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        hls_hotbm_fourth_o_33_reg_1376 = hls_hotbm_fourth_o_27_q0.read();
        hls_hotbm_fourth_o_35_reg_1381 = hls_hotbm_fourth_o_q0.read();
        p_Val2_19_reg_1361 = hls_hotbm_fourth_o_19_q0.read();
        tmp_23_i_reg_1366 = grp_fu_665_p2.read().range(107, 52);
        tmp_25_i_reg_1371 = grp_fu_677_p2.read().range(92, 45);
        tmp_96_i_reg_1351 = grp_fu_648_p2.read().range(97, 56);
        tmp_98_i_reg_1356 = grp_fu_653_p2.read().range(97, 63);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        not_do_cos_i_reg_1270 = not_do_cos_i_fu_612_p2.read();
        tmp_reg_1263 = tmp_fu_591_p10.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        p_Result_i_reg_1235 = p_Val2_14_fu_551_p3.read().range(62, 56);
        p_Val2_15_reg_1240 = p_Val2_15_fu_568_p1.read();
        tmp_i1_reg_1245 = p_Val2_14_fu_551_p3.read().range(55, 7);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        p_Val2_22_reg_1406 = p_Val2_22_fu_770_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_Val2_29_reg_1168 = p_Val2_29_fu_392_p3.read();
        p_Val2_i_reg_1179 = p_Val2_i_fu_402_p2.read();
        tmp_13_reg_1174 = tmp_13_fu_398_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        p_Val2_9_reg_1157 = grp_fu_361_p2.read().range(166, 43);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state31.read())) {
        result_V_reg_1447 = grp_fu_837_p2.read().range(125, 63);
        tmp_54_cast_reg_1452 = tmp_54_cast_fu_870_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ret_V_reg_1136 = r_V_4_fu_332_p2.read().range(255, 86);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        table_256_V_reg_1131 = hls_ref_4oPi_table_s_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        tmp_12_reg_1126 = tmp_12_fu_325_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        tmp_1_reg_1411 = grp_fu_736_p2.read().range(74, 38);
        tmp_2_reg_1416 = grp_fu_748_p2.read().range(59, 31);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(closepath_reg_1109.read(), ap_const_lv1_0))) {
        tmp_64_i_reg_1163 = grp_fu_361_p2.read().range(169, 167);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        tmp_7_reg_1151 = tmp_7_fu_367_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        tmp_99_i_reg_1276 = tmp_99_i_fu_629_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(closepath_reg_1109.read(), ap_const_lv1_1))) {
        tmp_i_reg_1184 = tmp_i_fu_407_p2.read();
    }
}

void sin_or_cos_double_s::thread_Ex_V_fu_502_p2() {
    Ex_V_fu_502_p2 = (!storemerge_i_fu_475_p3.read().is_01() || !tmp_68_i_fu_499_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(storemerge_i_fu_475_p3.read()) - sc_biguint<11>(tmp_68_i_fu_499_p1.read()));
}

void sin_or_cos_double_s::thread_Mx_V_read_assign_fu_807_p3() {
    Mx_V_read_assign_fu_807_p3 = (!cos_basis_fu_801_p3.read()[0].is_01())? sc_lv<63>(): ((cos_basis_fu_801_p3.read()[0].to_bool())? ap_const_lv63_7FFFFFFFFFFFFFFF: Mx_V_reg_1213.read());
}

void sin_or_cos_double_s::thread_Mx_zeros_V_fu_461_p1() {
    Mx_zeros_V_fu_461_p1 = tmp_i4_i_fu_453_p3.read().range(6-1, 0);
}

void sin_or_cos_double_s::thread_OP1_V_fu_582_p1() {
    OP1_V_fu_582_p1 = esl_zext<98,49>(tmp_i1_reg_1245.read());
}

void sin_or_cos_double_s::thread_OP2_V_fu_645_p1() {
    OP2_V_fu_645_p1 = esl_zext<98,49>(tmp_94_i_reg_1293.read());
}

void sin_or_cos_double_s::thread_addr_V_fu_304_p3() {
    addr_V_fu_304_p3 = (!closepath_reg_1109.read()[0].is_01())? sc_lv<11>(): ((closepath_reg_1109.read()[0].to_bool())? ap_const_lv11_4A: expv_op_reg_1116.read());
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read()[30];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[31];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void sin_or_cos_double_s::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void sin_or_cos_double_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()) && 
          esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_260_ap_done.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()) && 
         esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_260_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()) && 
         esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_260_ap_done.read(), ap_const_logic_1))) {
        ap_return = ret_i_i_fu_1086_p1.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void sin_or_cos_double_s::thread_closepath_fu_292_p2() {
    closepath_fu_292_p2 = (!loc_V_fu_278_p4.read().is_01() || !ap_const_lv11_3FE.is_01())? sc_lv<1>(): (sc_biguint<11>(loc_V_fu_278_p4.read()) < sc_biguint<11>(ap_const_lv11_3FE));
}

void sin_or_cos_double_s::thread_cos_basis_fu_801_p0() {
    cos_basis_fu_801_p0 =  (sc_lv<1>) (do_cos.read());
}

void sin_or_cos_double_s::thread_cos_basis_fu_801_p3() {
    cos_basis_fu_801_p3 = (!cos_basis_fu_801_p0.read()[0].is_01())? sc_lv<1>(): ((cos_basis_fu_801_p0.read()[0].to_bool())? tmp_s_fu_796_p2.read(): tmp_reg_1263.read());
}

void sin_or_cos_double_s::thread_expv_op_fu_298_p2() {
    expv_op_fu_298_p2 = (!ap_const_lv11_44D.is_01() || !loc_V_fu_278_p4.read().is_01())? sc_lv<11>(): (sc_bigint<11>(ap_const_lv11_44D) + sc_biguint<11>(loc_V_fu_278_p4.read()));
}

void sin_or_cos_double_s::thread_grp_fu_361_p0() {
    grp_fu_361_p0 =  (sc_lv<170>) (grp_fu_361_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_361_p00() {
    grp_fu_361_p00 = esl_zext<223,170>(ret_V_reg_1136.read());
}

void sin_or_cos_double_s::thread_grp_fu_361_p1() {
    grp_fu_361_p1 =  (sc_lv<53>) (grp_fu_361_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_361_p10() {
    grp_fu_361_p10 = esl_zext<223,53>(p_Result_20_fu_347_p3.read());
}

void sin_or_cos_double_s::thread_grp_fu_585_p0() {
    grp_fu_585_p0 =  (sc_lv<49>) (OP1_V_fu_582_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_585_p1() {
    grp_fu_585_p1 =  (sc_lv<49>) (OP1_V_fu_582_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_648_p0() {
    grp_fu_648_p0 =  (sc_lv<49>) (OP2_V_fu_645_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_648_p1() {
    grp_fu_648_p1 =  (sc_lv<49>) (OP1_V_reg_1250.read());
}

void sin_or_cos_double_s::thread_grp_fu_653_p0() {
    grp_fu_653_p0 =  (sc_lv<49>) (OP2_V_fu_645_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_653_p1() {
    grp_fu_653_p1 =  (sc_lv<49>) (OP2_V_fu_645_p1.read());
}

void sin_or_cos_double_s::thread_grp_fu_665_p0() {
    grp_fu_665_p0 =  (sc_lv<56>) (grp_fu_665_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_665_p00() {
    grp_fu_665_p00 = esl_zext<108,56>(p_Val2_15_reg_1240.read());
}

void sin_or_cos_double_s::thread_grp_fu_677_p0() {
    grp_fu_677_p0 =  (sc_lv<49>) (grp_fu_677_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_677_p00() {
    grp_fu_677_p00 = esl_zext<93,49>(tmp_94_i_reg_1293.read());
}

void sin_or_cos_double_s::thread_grp_fu_736_p0() {
    grp_fu_736_p0 =  (sc_lv<42>) (grp_fu_736_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_736_p00() {
    grp_fu_736_p00 = esl_zext<75,42>(tmp_96_i_reg_1351.read());
}

void sin_or_cos_double_s::thread_grp_fu_736_p1() {
    grp_fu_736_p1 =  (sc_lv<33>) (grp_fu_736_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_736_p10() {
    grp_fu_736_p10 = esl_zext<75,33>(hls_hotbm_fourth_o_33_reg_1376.read());
}

void sin_or_cos_double_s::thread_grp_fu_748_p0() {
    grp_fu_748_p0 =  (sc_lv<35>) (grp_fu_748_p00.read());
}

void sin_or_cos_double_s::thread_grp_fu_748_p00() {
    grp_fu_748_p00 = esl_zext<60,35>(tmp_98_i_reg_1356.read());
}

void sin_or_cos_double_s::thread_grp_fu_748_p1() {
    grp_fu_748_p1 =  (sc_lv<25>) (grp_fu_748_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_748_p10() {
    grp_fu_748_p10 = esl_zext<60,25>(hls_hotbm_fourth_o_35_reg_1381.read());
}

void sin_or_cos_double_s::thread_grp_fu_837_p1() {
    grp_fu_837_p1 =  (sc_lv<63>) (grp_fu_837_p10.read());
}

void sin_or_cos_double_s::thread_grp_fu_837_p10() {
    grp_fu_837_p10 = esl_zext<126,63>(Mx_V_read_assign_reg_1427.read());
}

void sin_or_cos_double_s::thread_grp_scaled_fixed2ieee_fu_260_ap_start() {
    grp_scaled_fixed2ieee_fu_260_ap_start = ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start.read();
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_19_address0() {
    hls_hotbm_fourth_o_19_address0 =  (sc_lv<8>) (tmp_99_i_reg_1276.read());
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_19_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        hls_hotbm_fourth_o_19_ce0 = ap_const_logic_1;
    } else {
        hls_hotbm_fourth_o_19_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_20_address0() {
    hls_hotbm_fourth_o_20_address0 =  (sc_lv<8>) (tmp_99_i_fu_629_p1.read());
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_20_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        hls_hotbm_fourth_o_20_ce0 = ap_const_logic_1;
    } else {
        hls_hotbm_fourth_o_20_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_21_address0() {
    hls_hotbm_fourth_o_21_address0 =  (sc_lv<8>) (tmp_99_i_fu_629_p1.read());
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_21_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        hls_hotbm_fourth_o_21_ce0 = ap_const_logic_1;
    } else {
        hls_hotbm_fourth_o_21_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_27_address0() {
    hls_hotbm_fourth_o_27_address0 =  (sc_lv<8>) (tmp_99_i_reg_1276.read());
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_27_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        hls_hotbm_fourth_o_27_ce0 = ap_const_logic_1;
    } else {
        hls_hotbm_fourth_o_27_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_address0() {
    hls_hotbm_fourth_o_address0 =  (sc_lv<8>) (tmp_99_i_reg_1276.read());
}

void sin_or_cos_double_s::thread_hls_hotbm_fourth_o_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        hls_hotbm_fourth_o_ce0 = ap_const_logic_1;
    } else {
        hls_hotbm_fourth_o_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_hls_ref_4oPi_table_s_address0() {
    hls_ref_4oPi_table_s_address0 =  (sc_lv<4>) (tmp_i2_i_fu_320_p1.read());
}

void sin_or_cos_double_s::thread_hls_ref_4oPi_table_s_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        hls_ref_4oPi_table_s_ce0 = ap_const_logic_1;
    } else {
        hls_ref_4oPi_table_s_ce0 = ap_const_logic_0;
    }
}

void sin_or_cos_double_s::thread_isNeg_fu_512_p3() {
    isNeg_fu_512_p3 = Ex_V_fu_502_p2.read().range(10, 10);
}

void sin_or_cos_double_s::thread_loc_V_1_fu_288_p1() {
    loc_V_1_fu_288_p1 = p_Val2_s_fu_266_p1.read().range(52-1, 0);
}

void sin_or_cos_double_s::thread_loc_V_2_fu_887_p4() {
    loc_V_2_fu_887_p4 = p_Val2_25_fu_875_p1.read().range(62, 52);
}

void sin_or_cos_double_s::thread_loc_V_3_fu_897_p1() {
    loc_V_3_fu_897_p1 = p_Val2_25_fu_875_p1.read().range(52-1, 0);
}

void sin_or_cos_double_s::thread_loc_V_fu_278_p4() {
    loc_V_fu_278_p4 = p_Val2_s_fu_266_p1.read().range(62, 52);
}

void sin_or_cos_double_s::thread_not_do_cos_i_fu_612_p0() {
    not_do_cos_i_fu_612_p0 =  (sc_lv<1>) (do_cos.read());
}

void sin_or_cos_double_s::thread_not_do_cos_i_fu_612_p2() {
    not_do_cos_i_fu_612_p2 = (not_do_cos_i_fu_612_p0.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_not_or_cond_demorgan_fu_1045_p2() {
    not_or_cond_demorgan_fu_1045_p2 = (tmp_6_reg_1200.read() & tmp_7_reg_1151.read());
}

void sin_or_cos_double_s::thread_not_or_cond_fu_1049_p2() {
    not_or_cond_fu_1049_p2 = (not_or_cond_demorgan_fu_1045_p2.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_not_tmp_s_fu_1011_p2() {
    not_tmp_s_fu_1011_p2 = (tmp_8_reg_1206.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_or_cond_fu_996_p2() {
    or_cond_fu_996_p2 = (tmp_6_reg_1200.read() & tmp_7_reg_1151.read());
}

void sin_or_cos_double_s::thread_p_Ex_V_ret_fu_843_p3() {
    p_Ex_V_ret_fu_843_p3 = (!cos_basis_reg_1421.read()[0].is_01())? sc_lv<11>(): ((cos_basis_reg_1421.read()[0].to_bool())? ap_const_lv11_0: Ex_V_reg_1220.read());
}

void sin_or_cos_double_s::thread_p_Result_1_fu_1000_p2() {
    p_Result_1_fu_1000_p2 = (p_Result_19_reg_1090.read() & not_do_cos_i_reg_1270.read());
}

void sin_or_cos_double_s::thread_p_Result_20_fu_347_p3() {
    p_Result_20_fu_347_p3 = esl_concat<1,52>(ap_const_lv1_1, loc_V_1_reg_1103.read());
}

void sin_or_cos_double_s::thread_p_Result_21_fu_427_p3() {
    p_Result_21_fu_427_p3 = esl_concat<61,1>(p_Result_i3_i_fu_417_p4.read(), ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_p_Result_22_fu_435_p4() {
    p_Result_22_fu_435_p4 = p_Result_21_fu_427_p3.read().range(0, 61);
}

void sin_or_cos_double_s::thread_p_Result_23_fu_445_p3() {
    p_Result_23_fu_445_p3 = esl_concat<2,62>(ap_const_lv2_3, p_Result_22_fu_435_p4.read());
}

void sin_or_cos_double_s::thread_p_Result_24_fu_622_p3() {
    p_Result_24_fu_622_p3 = esl_concat<1,7>(sin_basis_fu_618_p2.read(), p_Result_i_reg_1235.read());
}

void sin_or_cos_double_s::thread_p_Result_25_fu_879_p3() {
    p_Result_25_fu_879_p3 = p_Val2_25_fu_875_p1.read().range(63, 63);
}

void sin_or_cos_double_s::thread_p_Result_26_fu_901_p3() {
    p_Result_26_fu_901_p3 = esl_concat<1,3>(p_Result_19_reg_1090.read(), p_Val2_29_reg_1168.read());
}

void sin_or_cos_double_s::thread_p_Result_27_fu_1076_p4() {
    p_Result_27_fu_1076_p4 = esl_concat<12,52>(esl_concat<1,11>(p_Result_s_56_fu_1029_p3.read(), ret_V_6_fu_1037_p3.read()), ret_V_7_fu_1068_p3.read());
}

void sin_or_cos_double_s::thread_p_Result_2_fu_1022_p3() {
    p_Result_2_fu_1022_p3 = (!tmp_8_reg_1206.read()[0].is_01())? sc_lv<11>(): ((tmp_8_reg_1206.read()[0].to_bool())? ap_const_lv11_7FF: loc_V_2_fu_887_p4.read());
}

void sin_or_cos_double_s::thread_p_Result_3_cast_fu_1055_p3() {
    p_Result_3_cast_fu_1055_p3 = (!not_or_cond_fu_1049_p2.read()[0].is_01())? sc_lv<52>(): ((not_or_cond_fu_1049_p2.read()[0].to_bool())? ap_const_lv52_FFFFFFFFFFFFF: ap_const_lv52_0);
}

void sin_or_cos_double_s::thread_p_Result_i3_i_fu_417_p4() {
    p_Result_i3_i_fu_417_p4 = p_Val2_11_fu_412_p3.read().range(123, 63);
}

void sin_or_cos_double_s::thread_p_Result_i_i_fu_310_p4() {
    p_Result_i_i_fu_310_p4 = addr_V_fu_304_p3.read().range(10, 7);
}

void sin_or_cos_double_s::thread_p_Result_s_55_fu_1016_p2() {
    p_Result_s_55_fu_1016_p2 = (p_Result_s_fu_990_p2.read() & not_tmp_s_fu_1011_p2.read());
}

void sin_or_cos_double_s::thread_p_Result_s_56_fu_1029_p3() {
    p_Result_s_56_fu_1029_p3 = (!or_cond_fu_996_p2.read()[0].is_01())? sc_lv<1>(): ((or_cond_fu_996_p2.read()[0].to_bool())? p_Result_1_fu_1000_p2.read(): p_Result_s_55_fu_1016_p2.read());
}

void sin_or_cos_double_s::thread_p_Result_s_fu_990_p2() {
    p_Result_s_fu_990_p2 = (tmp_5_fu_983_p3.read() | p_Result_25_fu_879_p3.read());
}

void sin_or_cos_double_s::thread_p_Val2_11_fu_412_p3() {
    p_Val2_11_fu_412_p3 = (!tmp_13_reg_1174.read()[0].is_01())? sc_lv<124>(): ((tmp_13_reg_1174.read()[0].to_bool())? p_Val2_i_reg_1179.read(): p_Val2_9_reg_1157.read());
}

void sin_or_cos_double_s::thread_p_Val2_13_fu_484_p2() {
    p_Val2_13_fu_484_p2 = (!tmp_65_i_fu_481_p1.read().is_01())? sc_lv<124>(): p_Val2_11_reg_1189.read() << (unsigned short)tmp_65_i_fu_481_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_p_Val2_14_fu_551_p3() {
    p_Val2_14_fu_551_p3 = (!isNeg_reg_1225.read()[0].is_01())? sc_lv<63>(): ((isNeg_reg_1225.read()[0].to_bool())? tmp_72_i_fu_541_p2.read(): tmp_73_i_fu_546_p2.read());
}

void sin_or_cos_double_s::thread_p_Val2_15_fu_568_p1() {
    p_Val2_15_fu_568_p1 = p_Val2_14_fu_551_p3.read().range(56-1, 0);
}

void sin_or_cos_double_s::thread_p_Val2_20_fu_723_p3() {
    p_Val2_20_fu_723_p3 = esl_concat<59,4>(p_Val2_19_reg_1361.read(), ap_const_lv4_0);
}

void sin_or_cos_double_s::thread_p_Val2_21_fu_761_p2() {
    p_Val2_21_fu_761_p2 = (!tmp_101_i_fu_754_p1.read().is_01() || !tmp_102_i_fu_758_p1.read().is_01())? sc_lv<64>(): (sc_bigint<64>(tmp_101_i_fu_754_p1.read()) + sc_bigint<64>(tmp_102_i_fu_758_p1.read()));
}

void sin_or_cos_double_s::thread_p_Val2_22_fu_770_p2() {
    p_Val2_22_fu_770_p2 = (!p_Val2_21_fu_761_p2.read().is_01() || !tmp_104_i_cast_fu_767_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_Val2_21_fu_761_p2.read()) + sc_bigint<64>(tmp_104_i_cast_fu_767_p1.read()));
}

void sin_or_cos_double_s::thread_p_Val2_23_fu_817_p2() {
    p_Val2_23_fu_817_p2 = (!p_Val2_22_reg_1406.read().is_01() || !tmp_106_i_cast_fu_814_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_Val2_22_reg_1406.read()) + sc_biguint<64>(tmp_106_i_cast_fu_814_p1.read()));
}

void sin_or_cos_double_s::thread_p_Val2_25_fu_875_p1() {
    p_Val2_25_fu_875_p1 = grp_scaled_fixed2ieee_fu_260_ap_return.read();
}

void sin_or_cos_double_s::thread_p_Val2_29_fu_392_p3() {
    p_Val2_29_fu_392_p3 = (!closepath_reg_1109.read()[0].is_01())? sc_lv<3>(): ((closepath_reg_1109.read()[0].to_bool())? ap_const_lv3_0: tmp_64_i_reg_1163.read());
}

void sin_or_cos_double_s::thread_p_Val2_i_fu_402_p2() {
    p_Val2_i_fu_402_p2 = (!ap_const_lv124_0.is_01() || !p_Val2_9_reg_1157.read().is_01())? sc_lv<124>(): (sc_biguint<124>(ap_const_lv124_0) - sc_biguint<124>(p_Val2_9_reg_1157.read()));
}

void sin_or_cos_double_s::thread_p_Val2_s_fu_266_p1() {
    p_Val2_s_fu_266_p1 = t_in.read();
}

void sin_or_cos_double_s::thread_p_cast_cast_fu_1004_p0() {
    p_cast_cast_fu_1004_p0 =  (sc_lv<1>) (do_cos.read());
}

void sin_or_cos_double_s::thread_p_cast_cast_fu_1004_p3() {
    p_cast_cast_fu_1004_p3 = (!p_cast_cast_fu_1004_p0.read()[0].is_01())? sc_lv<11>(): ((p_cast_cast_fu_1004_p0.read()[0].to_bool())? ap_const_lv11_3FF: ap_const_lv11_0);
}

void sin_or_cos_double_s::thread_r_V_3_fu_825_p2() {
    r_V_3_fu_825_p2 = (!p_Val2_23_fu_817_p2.read().is_01() || !tmp_108_i_cast_fu_822_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(p_Val2_23_fu_817_p2.read()) + sc_biguint<64>(tmp_108_i_cast_fu_822_p1.read()));
}

void sin_or_cos_double_s::thread_r_V_4_fu_332_p2() {
    r_V_4_fu_332_p2 = (!tmp_52_i_i_fu_329_p1.read().is_01())? sc_lv<256>(): table_256_V_reg_1131.read() << (unsigned short)tmp_52_i_i_fu_329_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_r_V_fu_864_p2() {
    r_V_fu_864_p2 = (!ap_const_lv12_0.is_01() || !rhs_V_fu_860_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_bigint<12>(rhs_V_fu_860_p1.read()));
}

void sin_or_cos_double_s::thread_ret_V_6_fu_1037_p3() {
    ret_V_6_fu_1037_p3 = (!or_cond_fu_996_p2.read()[0].is_01())? sc_lv<11>(): ((or_cond_fu_996_p2.read()[0].to_bool())? p_cast_cast_fu_1004_p3.read(): p_Result_2_fu_1022_p3.read());
}

void sin_or_cos_double_s::thread_ret_V_7_fu_1068_p3() {
    ret_V_7_fu_1068_p3 = (!tmp_9_fu_1063_p2.read()[0].is_01())? sc_lv<52>(): ((tmp_9_fu_1063_p2.read()[0].to_bool())? p_Result_3_cast_fu_1055_p3.read(): loc_V_3_fu_897_p1.read());
}

void sin_or_cos_double_s::thread_ret_i_i_fu_1086_p1() {
    ret_i_i_fu_1086_p1 = p_Result_27_fu_1076_p4.read();
}

void sin_or_cos_double_s::thread_rhs_V_fu_860_p1() {
    rhs_V_fu_860_p1 = esl_sext<12,11>(p_Ex_V_ret_fu_843_p3.read());
}

void sin_or_cos_double_s::thread_sh_assign_4_cast_fu_534_p1() {
    sh_assign_4_cast_fu_534_p1 = esl_sext<32,12>(sh_assign_reg_1230.read());
}

void sin_or_cos_double_s::thread_sh_assign_fu_526_p3() {
    sh_assign_fu_526_p3 = (!isNeg_fu_512_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_fu_512_p3.read()[0].to_bool())? tmp_70_i_fu_520_p2.read(): sh_cast_fu_508_p1.read());
}

void sin_or_cos_double_s::thread_sh_cast_fu_508_p1() {
    sh_cast_fu_508_p1 = esl_sext<12,11>(Ex_V_fu_502_p2.read());
}

void sin_or_cos_double_s::thread_sin_basis_fu_618_p2() {
    sin_basis_fu_618_p2 = (tmp_reg_1263.read() ^ not_do_cos_i_reg_1270.read());
}

void sin_or_cos_double_s::thread_storemerge_i_fu_475_p3() {
    storemerge_i_fu_475_p3 = (!closepath_reg_1109.read()[0].is_01())? sc_lv<11>(): ((closepath_reg_1109.read()[0].to_bool())? tmp_i_reg_1184.read(): ap_const_lv11_0);
}

void sin_or_cos_double_s::thread_tmp_101_i_fu_754_p1() {
    tmp_101_i_fu_754_p1 = esl_sext<64,63>(p_Val2_20_fu_723_p3.read());
}

void sin_or_cos_double_s::thread_tmp_102_i_fu_758_p1() {
    tmp_102_i_fu_758_p1 = esl_sext<64,56>(tmp_23_i_reg_1366.read());
}

void sin_or_cos_double_s::thread_tmp_104_i_cast_fu_767_p1() {
    tmp_104_i_cast_fu_767_p1 = esl_sext<64,48>(tmp_25_i_reg_1371.read());
}

void sin_or_cos_double_s::thread_tmp_106_i_cast_fu_814_p1() {
    tmp_106_i_cast_fu_814_p1 = esl_zext<64,37>(tmp_1_reg_1411.read());
}

void sin_or_cos_double_s::thread_tmp_108_i_cast_fu_822_p1() {
    tmp_108_i_cast_fu_822_p1 = esl_zext<64,29>(tmp_2_reg_1416.read());
}

void sin_or_cos_double_s::thread_tmp_12_fu_325_p1() {
    tmp_12_fu_325_p1 = addr_V_fu_304_p3.read().range(7-1, 0);
}

void sin_or_cos_double_s::thread_tmp_13_fu_398_p1() {
    tmp_13_fu_398_p1 = p_Val2_29_fu_392_p3.read().range(1-1, 0);
}

void sin_or_cos_double_s::thread_tmp_52_i_i_fu_329_p1() {
    tmp_52_i_i_fu_329_p1 = esl_zext<256,7>(tmp_12_reg_1126.read());
}

void sin_or_cos_double_s::thread_tmp_54_cast_fu_870_p1() {
    tmp_54_cast_fu_870_p1 = esl_sext<13,12>(r_V_fu_864_p2.read());
}

void sin_or_cos_double_s::thread_tmp_5_fu_983_p3() {
    tmp_5_fu_983_p3 = (!cos_basis_reg_1421.read()[0].is_01())? sc_lv<1>(): ((cos_basis_reg_1421.read()[0].to_bool())? tmp_3_fu_907_p18.read(): tmp_4_fu_945_p18.read());
}

void sin_or_cos_double_s::thread_tmp_65_i_fu_481_p1() {
    tmp_65_i_fu_481_p1 = esl_zext<124,6>(Mx_zeros_V_reg_1194.read());
}

void sin_or_cos_double_s::thread_tmp_68_i_fu_499_p1() {
    tmp_68_i_fu_499_p1 = esl_zext<11,6>(Mx_zeros_V_reg_1194.read());
}

void sin_or_cos_double_s::thread_tmp_6_fu_465_p2() {
    tmp_6_fu_465_p2 = (!loc_V_reg_1096.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_1096.read() == ap_const_lv11_0);
}

void sin_or_cos_double_s::thread_tmp_70_i_fu_520_p2() {
    tmp_70_i_fu_520_p2 = (!ap_const_lv12_0.is_01() || !sh_cast_fu_508_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_bigint<12>(sh_cast_fu_508_p1.read()));
}

void sin_or_cos_double_s::thread_tmp_71_i_fu_537_p1() {
    tmp_71_i_fu_537_p1 = esl_zext<63,32>(sh_assign_4_cast_fu_534_p1.read());
}

void sin_or_cos_double_s::thread_tmp_72_i_fu_541_p2() {
    tmp_72_i_fu_541_p2 = (!tmp_71_i_fu_537_p1.read().is_01())? sc_lv<63>(): Mx_V_reg_1213.read() >> (unsigned short)tmp_71_i_fu_537_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_tmp_73_i_fu_546_p2() {
    tmp_73_i_fu_546_p2 = (!tmp_71_i_fu_537_p1.read().is_01())? sc_lv<63>(): Mx_V_reg_1213.read() << (unsigned short)tmp_71_i_fu_537_p1.read().to_uint();
}

void sin_or_cos_double_s::thread_tmp_7_fu_367_p2() {
    tmp_7_fu_367_p2 = (!loc_V_1_reg_1103.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_1_reg_1103.read() == ap_const_lv52_0);
}

void sin_or_cos_double_s::thread_tmp_8_fu_470_p2() {
    tmp_8_fu_470_p2 = (!loc_V_reg_1096.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_reg_1096.read() == ap_const_lv11_7FF);
}

void sin_or_cos_double_s::thread_tmp_99_i_fu_629_p1() {
    tmp_99_i_fu_629_p1 = esl_zext<32,8>(p_Result_24_fu_622_p3.read());
}

void sin_or_cos_double_s::thread_tmp_9_fu_1063_p2() {
    tmp_9_fu_1063_p2 = (or_cond_fu_996_p2.read() | tmp_8_reg_1206.read());
}

void sin_or_cos_double_s::thread_tmp_i2_i_fu_320_p1() {
    tmp_i2_i_fu_320_p1 = esl_zext<32,4>(p_Result_i_i_fu_310_p4.read());
}

void sin_or_cos_double_s::thread_tmp_i4_i_fu_453_p3() {
    tmp_i4_i_fu_453_p3 = esl_cttz<64,64>(p_Result_23_fu_445_p3.read());
}

void sin_or_cos_double_s::thread_tmp_i_fu_407_p2() {
    tmp_i_fu_407_p2 = (!ap_const_lv11_403.is_01() || !loc_V_reg_1096.read().is_01())? sc_lv<11>(): (sc_bigint<11>(ap_const_lv11_403) + sc_biguint<11>(loc_V_reg_1096.read()));
}

void sin_or_cos_double_s::thread_tmp_s_fu_796_p2() {
    tmp_s_fu_796_p2 = (tmp_reg_1263.read() ^ ap_const_lv1_1);
}

void sin_or_cos_double_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()) && esl_seteq<1,1,1>(grp_scaled_fixed2ieee_fu_260_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state32;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

}

