-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity p_hls_fptosi_float_i is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of p_hls_fptosi_float_i is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_Result_s_reg_186 : STD_LOGIC_VECTOR (0 downto 0);
    signal loc_V_1_fu_66_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal loc_V_1_reg_191 : STD_LOGIC_VECTOR (22 downto 0);
    signal isNeg_fu_80_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_196 : STD_LOGIC_VECTOR (0 downto 0);
    signal sh_assign_1_fu_98_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sh_assign_1_reg_201 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_2_fu_163_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_2_reg_207 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_Val2_s_fu_44_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal loc_V_fu_56_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_i_i_cast1_fu_70_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sh_assign_fu_74_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_i_i_fu_88_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_i_i_cast_fu_94_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_1_i_i_fu_106_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sh_assign_1_cast_fu_119_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sh_assign_1_cast_cas_fu_122_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_1_i_i_cast2_fu_115_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_3_i_i_fu_125_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_4_i_i_fu_129_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_fu_141_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_i_i_fu_135_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_16_fu_149_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_fu_153_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_7_i_i_fu_170_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_i_i_fu_173_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                isNeg_reg_196 <= sh_assign_fu_74_p2(8 downto 8);
                loc_V_1_reg_191 <= loc_V_1_fu_66_p1;
                p_Result_s_reg_186 <= p_Val2_s_fu_44_p1(31 downto 31);
                sh_assign_1_reg_201 <= sh_assign_1_fu_98_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_Val2_2_reg_207 <= p_Val2_2_fu_163_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1)) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        tmp_10_i_i_fu_173_p2 when (p_Result_s_reg_186(0) = '1') else 
        tmp_7_i_i_fu_170_p1;
    isNeg_fu_80_p3 <= sh_assign_fu_74_p2(8 downto 8);
    loc_V_1_fu_66_p1 <= p_Val2_s_fu_44_p1(23 - 1 downto 0);
    loc_V_fu_56_p4 <= p_Val2_s_fu_44_p1(30 downto 23);
    p_Val2_2_fu_163_p3 <= 
        tmp_16_fu_149_p1 when (isNeg_reg_196(0) = '1') else 
        tmp_s_fu_153_p4;
    p_Val2_s_fu_44_p1 <= x;
        sh_assign_1_cast_cas_fu_122_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_assign_1_reg_201),25));

        sh_assign_1_cast_fu_119_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_assign_1_reg_201),32));

    sh_assign_1_fu_98_p3 <= 
        tmp_2_i_i_cast_fu_94_p1 when (isNeg_fu_80_p3(0) = '1') else 
        sh_assign_fu_74_p2;
    sh_assign_fu_74_p2 <= std_logic_vector(signed(ap_const_lv9_181) + signed(tmp_i_i_i_cast1_fu_70_p1));
    tmp_10_i_i_fu_173_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(tmp_7_i_i_fu_170_p1));
    tmp_16_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_141_p3),15));
    tmp_1_i_i_cast2_fu_115_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_i_i_fu_106_p4),63));
    tmp_1_i_i_fu_106_p4 <= ((ap_const_lv1_1 & loc_V_1_reg_191) & ap_const_lv1_0);
        tmp_2_i_i_cast_fu_94_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_i_i_fu_88_p2),9));

    tmp_2_i_i_fu_88_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(loc_V_fu_56_p4));
    tmp_3_i_i_fu_125_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_assign_1_cast_fu_119_p1),63));
    tmp_4_i_i_fu_129_p2 <= std_logic_vector(shift_right(unsigned(tmp_1_i_i_fu_106_p4),to_integer(unsigned('0' & sh_assign_1_cast_cas_fu_122_p1(25-1 downto 0)))));
    tmp_5_i_i_fu_135_p2 <= std_logic_vector(shift_left(unsigned(tmp_1_i_i_cast2_fu_115_p1),to_integer(unsigned('0' & tmp_3_i_i_fu_125_p1(31-1 downto 0)))));
    tmp_7_i_i_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_2_reg_207),16));
    tmp_fu_141_p3 <= tmp_4_i_i_fu_129_p2(24 downto 24);
    tmp_i_i_i_cast1_fu_70_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loc_V_fu_56_p4),9));
    tmp_s_fu_153_p4 <= tmp_5_i_i_fu_135_p2(38 downto 24);
end behav;
