// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xconvolve.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XConvolve_CfgInitialize(XConvolve *InstancePtr, XConvolve_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Conv_BaseAddress = ConfigPtr->Conv_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XConvolve_Start(XConvolve *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolve_ReadReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_AP_CTRL) & 0x80;
    XConvolve_WriteReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_AP_CTRL, Data | 0x01);
}

u32 XConvolve_IsDone(XConvolve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolve_ReadReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XConvolve_IsIdle(XConvolve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolve_ReadReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XConvolve_IsReady(XConvolve *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolve_ReadReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XConvolve_EnableAutoRestart(XConvolve *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolve_WriteReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_AP_CTRL, 0x80);
}

void XConvolve_DisableAutoRestart(XConvolve *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolve_WriteReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_AP_CTRL, 0);
}

u32 XConvolve_Get_in_r_BaseAddress(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_IN_R_BASE);
}

u32 XConvolve_Get_in_r_HighAddress(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_IN_R_HIGH);
}

u32 XConvolve_Get_in_r_TotalBytes(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCONVOLVE_CONV_ADDR_IN_R_HIGH - XCONVOLVE_CONV_ADDR_IN_R_BASE + 1);
}

u32 XConvolve_Get_in_r_BitWidth(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVE_CONV_WIDTH_IN_R;
}

u32 XConvolve_Get_in_r_Depth(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVE_CONV_DEPTH_IN_R;
}

u32 XConvolve_Write_in_r_Words(XConvolve *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVE_CONV_ADDR_IN_R_HIGH - XCONVOLVE_CONV_ADDR_IN_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_IN_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XConvolve_Read_in_r_Words(XConvolve *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVE_CONV_ADDR_IN_R_HIGH - XCONVOLVE_CONV_ADDR_IN_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_IN_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XConvolve_Write_in_r_Bytes(XConvolve *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVE_CONV_ADDR_IN_R_HIGH - XCONVOLVE_CONV_ADDR_IN_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_IN_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XConvolve_Read_in_r_Bytes(XConvolve *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVE_CONV_ADDR_IN_R_HIGH - XCONVOLVE_CONV_ADDR_IN_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_IN_R_BASE + offset + i);
    }
    return length;
}

u32 XConvolve_Get_out_r_BaseAddress(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_OUT_R_BASE);
}

u32 XConvolve_Get_out_r_HighAddress(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_OUT_R_HIGH);
}

u32 XConvolve_Get_out_r_TotalBytes(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCONVOLVE_CONV_ADDR_OUT_R_HIGH - XCONVOLVE_CONV_ADDR_OUT_R_BASE + 1);
}

u32 XConvolve_Get_out_r_BitWidth(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVE_CONV_WIDTH_OUT_R;
}

u32 XConvolve_Get_out_r_Depth(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVE_CONV_DEPTH_OUT_R;
}

u32 XConvolve_Write_out_r_Words(XConvolve *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVE_CONV_ADDR_OUT_R_HIGH - XCONVOLVE_CONV_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_OUT_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XConvolve_Read_out_r_Words(XConvolve *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVE_CONV_ADDR_OUT_R_HIGH - XCONVOLVE_CONV_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_OUT_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XConvolve_Write_out_r_Bytes(XConvolve *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVE_CONV_ADDR_OUT_R_HIGH - XCONVOLVE_CONV_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_OUT_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XConvolve_Read_out_r_Bytes(XConvolve *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVE_CONV_ADDR_OUT_R_HIGH - XCONVOLVE_CONV_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_OUT_R_BASE + offset + i);
    }
    return length;
}

u32 XConvolve_Get_krnl_BaseAddress(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_KRNL_BASE);
}

u32 XConvolve_Get_krnl_HighAddress(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_KRNL_HIGH);
}

u32 XConvolve_Get_krnl_TotalBytes(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCONVOLVE_CONV_ADDR_KRNL_HIGH - XCONVOLVE_CONV_ADDR_KRNL_BASE + 1);
}

u32 XConvolve_Get_krnl_BitWidth(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVE_CONV_WIDTH_KRNL;
}

u32 XConvolve_Get_krnl_Depth(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVE_CONV_DEPTH_KRNL;
}

u32 XConvolve_Write_krnl_Words(XConvolve *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVE_CONV_ADDR_KRNL_HIGH - XCONVOLVE_CONV_ADDR_KRNL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_KRNL_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XConvolve_Read_krnl_Words(XConvolve *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVE_CONV_ADDR_KRNL_HIGH - XCONVOLVE_CONV_ADDR_KRNL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_KRNL_BASE + (offset + i)*4);
    }
    return length;
}

u32 XConvolve_Write_krnl_Bytes(XConvolve *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVE_CONV_ADDR_KRNL_HIGH - XCONVOLVE_CONV_ADDR_KRNL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_KRNL_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XConvolve_Read_krnl_Bytes(XConvolve *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVE_CONV_ADDR_KRNL_HIGH - XCONVOLVE_CONV_ADDR_KRNL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Conv_BaseAddress + XCONVOLVE_CONV_ADDR_KRNL_BASE + offset + i);
    }
    return length;
}

void XConvolve_InterruptGlobalEnable(XConvolve *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolve_WriteReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_GIE, 1);
}

void XConvolve_InterruptGlobalDisable(XConvolve *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolve_WriteReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_GIE, 0);
}

void XConvolve_InterruptEnable(XConvolve *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConvolve_ReadReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_IER);
    XConvolve_WriteReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_IER, Register | Mask);
}

void XConvolve_InterruptDisable(XConvolve *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConvolve_ReadReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_IER);
    XConvolve_WriteReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_IER, Register & (~Mask));
}

void XConvolve_InterruptClear(XConvolve *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolve_WriteReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_ISR, Mask);
}

u32 XConvolve_InterruptGetEnabled(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConvolve_ReadReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_IER);
}

u32 XConvolve_InterruptGetStatus(XConvolve *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConvolve_ReadReg(InstancePtr->Conv_BaseAddress, XCONVOLVE_CONV_ADDR_ISR);
}

