// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xconvolve.h"

extern XConvolve_Config XConvolve_ConfigTable[];

XConvolve_Config *XConvolve_LookupConfig(u16 DeviceId) {
	XConvolve_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XCONVOLVE_NUM_INSTANCES; Index++) {
		if (XConvolve_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XConvolve_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XConvolve_Initialize(XConvolve *InstancePtr, u16 DeviceId) {
	XConvolve_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XConvolve_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XConvolve_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

