// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xconvolvemedium.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XConvolvemedium_CfgInitialize(XConvolvemedium *InstancePtr, XConvolvemedium_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Convm_BaseAddress = ConfigPtr->Convm_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XConvolvemedium_Start(XConvolvemedium *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolvemedium_ReadReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_AP_CTRL) & 0x80;
    XConvolvemedium_WriteReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_AP_CTRL, Data | 0x01);
}

u32 XConvolvemedium_IsDone(XConvolvemedium *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolvemedium_ReadReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XConvolvemedium_IsIdle(XConvolvemedium *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolvemedium_ReadReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XConvolvemedium_IsReady(XConvolvemedium *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XConvolvemedium_ReadReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XConvolvemedium_EnableAutoRestart(XConvolvemedium *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolvemedium_WriteReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_AP_CTRL, 0x80);
}

void XConvolvemedium_DisableAutoRestart(XConvolvemedium *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolvemedium_WriteReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_AP_CTRL, 0);
}

u32 XConvolvemedium_Get_in_r_BaseAddress(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE);
}

u32 XConvolvemedium_Get_in_r_HighAddress(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_HIGH);
}

u32 XConvolvemedium_Get_in_r_TotalBytes(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE + 1);
}

u32 XConvolvemedium_Get_in_r_BitWidth(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVEMEDIUM_CONVM_WIDTH_IN_R;
}

u32 XConvolvemedium_Get_in_r_Depth(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVEMEDIUM_CONVM_DEPTH_IN_R;
}

u32 XConvolvemedium_Write_in_r_Words(XConvolvemedium *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XConvolvemedium_Read_in_r_Words(XConvolvemedium *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XConvolvemedium_Write_in_r_Bytes(XConvolvemedium *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XConvolvemedium_Read_in_r_Bytes(XConvolvemedium *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_IN_R_BASE + offset + i);
    }
    return length;
}

u32 XConvolvemedium_Get_out_r_BaseAddress(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE);
}

u32 XConvolvemedium_Get_out_r_HighAddress(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_HIGH);
}

u32 XConvolvemedium_Get_out_r_TotalBytes(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE + 1);
}

u32 XConvolvemedium_Get_out_r_BitWidth(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVEMEDIUM_CONVM_WIDTH_OUT_R;
}

u32 XConvolvemedium_Get_out_r_Depth(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVEMEDIUM_CONVM_DEPTH_OUT_R;
}

u32 XConvolvemedium_Write_out_r_Words(XConvolvemedium *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XConvolvemedium_Read_out_r_Words(XConvolvemedium *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XConvolvemedium_Write_out_r_Bytes(XConvolvemedium *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XConvolvemedium_Read_out_r_Bytes(XConvolvemedium *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_OUT_R_BASE + offset + i);
    }
    return length;
}

u32 XConvolvemedium_Get_krnl_BaseAddress(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE);
}

u32 XConvolvemedium_Get_krnl_HighAddress(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_HIGH);
}

u32 XConvolvemedium_Get_krnl_TotalBytes(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE + 1);
}

u32 XConvolvemedium_Get_krnl_BitWidth(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVEMEDIUM_CONVM_WIDTH_KRNL;
}

u32 XConvolvemedium_Get_krnl_Depth(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCONVOLVEMEDIUM_CONVM_DEPTH_KRNL;
}

u32 XConvolvemedium_Write_krnl_Words(XConvolvemedium *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XConvolvemedium_Read_krnl_Words(XConvolvemedium *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE + (offset + i)*4);
    }
    return length;
}

u32 XConvolvemedium_Write_krnl_Bytes(XConvolvemedium *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XConvolvemedium_Read_krnl_Bytes(XConvolvemedium *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_HIGH - XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Convm_BaseAddress + XCONVOLVEMEDIUM_CONVM_ADDR_KRNL_BASE + offset + i);
    }
    return length;
}

void XConvolvemedium_InterruptGlobalEnable(XConvolvemedium *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolvemedium_WriteReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_GIE, 1);
}

void XConvolvemedium_InterruptGlobalDisable(XConvolvemedium *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolvemedium_WriteReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_GIE, 0);
}

void XConvolvemedium_InterruptEnable(XConvolvemedium *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConvolvemedium_ReadReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_IER);
    XConvolvemedium_WriteReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_IER, Register | Mask);
}

void XConvolvemedium_InterruptDisable(XConvolvemedium *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XConvolvemedium_ReadReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_IER);
    XConvolvemedium_WriteReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_IER, Register & (~Mask));
}

void XConvolvemedium_InterruptClear(XConvolvemedium *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XConvolvemedium_WriteReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_ISR, Mask);
}

u32 XConvolvemedium_InterruptGetEnabled(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConvolvemedium_ReadReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_IER);
}

u32 XConvolvemedium_InterruptGetStatus(XConvolvemedium *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XConvolvemedium_ReadReg(InstancePtr->Convm_BaseAddress, XCONVOLVEMEDIUM_CONVM_ADDR_ISR);
}

