// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sin_or_cos_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t_in,
        do_cos,
        ap_return
);

parameter    ap_ST_fsm_state1 = 32'd1;
parameter    ap_ST_fsm_state2 = 32'd2;
parameter    ap_ST_fsm_state3 = 32'd4;
parameter    ap_ST_fsm_state4 = 32'd8;
parameter    ap_ST_fsm_state5 = 32'd16;
parameter    ap_ST_fsm_state6 = 32'd32;
parameter    ap_ST_fsm_state7 = 32'd64;
parameter    ap_ST_fsm_state8 = 32'd128;
parameter    ap_ST_fsm_state9 = 32'd256;
parameter    ap_ST_fsm_state10 = 32'd512;
parameter    ap_ST_fsm_state11 = 32'd1024;
parameter    ap_ST_fsm_state12 = 32'd2048;
parameter    ap_ST_fsm_state13 = 32'd4096;
parameter    ap_ST_fsm_state14 = 32'd8192;
parameter    ap_ST_fsm_state15 = 32'd16384;
parameter    ap_ST_fsm_state16 = 32'd32768;
parameter    ap_ST_fsm_state17 = 32'd65536;
parameter    ap_ST_fsm_state18 = 32'd131072;
parameter    ap_ST_fsm_state19 = 32'd262144;
parameter    ap_ST_fsm_state20 = 32'd524288;
parameter    ap_ST_fsm_state21 = 32'd1048576;
parameter    ap_ST_fsm_state22 = 32'd2097152;
parameter    ap_ST_fsm_state23 = 32'd4194304;
parameter    ap_ST_fsm_state24 = 32'd8388608;
parameter    ap_ST_fsm_state25 = 32'd16777216;
parameter    ap_ST_fsm_state26 = 32'd33554432;
parameter    ap_ST_fsm_state27 = 32'd67108864;
parameter    ap_ST_fsm_state28 = 32'd134217728;
parameter    ap_ST_fsm_state29 = 32'd268435456;
parameter    ap_ST_fsm_state30 = 32'd536870912;
parameter    ap_ST_fsm_state31 = 32'd1073741824;
parameter    ap_ST_fsm_state32 = 32'd2147483648;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] t_in;
input   do_cos;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] hls_ref_4oPi_table_s_address0;
reg    hls_ref_4oPi_table_s_ce0;
wire   [255:0] hls_ref_4oPi_table_s_q0;
wire   [7:0] hls_hotbm_fourth_o_19_address0;
reg    hls_hotbm_fourth_o_19_ce0;
wire   [58:0] hls_hotbm_fourth_o_19_q0;
wire   [7:0] hls_hotbm_fourth_o_20_address0;
reg    hls_hotbm_fourth_o_20_ce0;
wire   [51:0] hls_hotbm_fourth_o_20_q0;
wire   [7:0] hls_hotbm_fourth_o_21_address0;
reg    hls_hotbm_fourth_o_21_ce0;
wire   [43:0] hls_hotbm_fourth_o_21_q0;
wire   [7:0] hls_hotbm_fourth_o_27_address0;
reg    hls_hotbm_fourth_o_27_ce0;
wire   [32:0] hls_hotbm_fourth_o_27_q0;
wire   [7:0] hls_hotbm_fourth_o_address0;
reg    hls_hotbm_fourth_o_ce0;
wire   [24:0] hls_hotbm_fourth_o_q0;
reg   [0:0] p_Result_19_reg_1090;
wire   [10:0] loc_V_fu_278_p4;
reg   [10:0] loc_V_reg_1096;
wire   [51:0] loc_V_1_fu_288_p1;
reg   [51:0] loc_V_1_reg_1103;
wire   [0:0] closepath_fu_292_p2;
reg   [0:0] closepath_reg_1109;
wire   [10:0] expv_op_fu_298_p2;
reg   [10:0] expv_op_reg_1116;
wire    ap_CS_fsm_state2;
wire   [6:0] tmp_12_fu_325_p1;
reg   [6:0] tmp_12_reg_1126;
reg   [255:0] table_256_V_reg_1131;
wire    ap_CS_fsm_state3;
reg   [169:0] ret_V_reg_1136;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [0:0] tmp_7_fu_367_p2;
reg   [0:0] tmp_7_reg_1151;
reg   [123:0] p_Val2_9_reg_1157;
wire    ap_CS_fsm_state9;
reg   [2:0] tmp_64_i_reg_1163;
wire   [2:0] p_Val2_29_fu_392_p3;
reg   [2:0] p_Val2_29_reg_1168;
wire    ap_CS_fsm_state10;
wire   [0:0] tmp_13_fu_398_p1;
reg   [0:0] tmp_13_reg_1174;
wire   [123:0] p_Val2_i_fu_402_p2;
reg   [123:0] p_Val2_i_reg_1179;
wire   [10:0] tmp_i_fu_407_p2;
reg   [10:0] tmp_i_reg_1184;
wire    ap_CS_fsm_state11;
wire   [123:0] p_Val2_11_fu_412_p3;
reg   [123:0] p_Val2_11_reg_1189;
wire   [5:0] Mx_zeros_V_fu_461_p1;
reg   [5:0] Mx_zeros_V_reg_1194;
wire   [0:0] tmp_6_fu_465_p2;
reg   [0:0] tmp_6_reg_1200;
wire   [0:0] tmp_8_fu_470_p2;
reg   [0:0] tmp_8_reg_1206;
reg   [62:0] Mx_V_reg_1213;
wire    ap_CS_fsm_state12;
wire   [10:0] Ex_V_fu_502_p2;
reg   [10:0] Ex_V_reg_1220;
wire   [0:0] isNeg_fu_512_p3;
reg   [0:0] isNeg_reg_1225;
wire   [11:0] sh_assign_fu_526_p3;
reg   [11:0] sh_assign_reg_1230;
reg   [6:0] p_Result_i_reg_1235;
wire    ap_CS_fsm_state13;
wire   [55:0] p_Val2_15_fu_568_p1;
reg   [55:0] p_Val2_15_reg_1240;
reg   [48:0] tmp_i1_reg_1245;
wire   [97:0] OP1_V_fu_582_p1;
reg   [97:0] OP1_V_reg_1250;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state16;
wire   [0:0] tmp_fu_591_p10;
reg   [0:0] tmp_reg_1263;
wire   [0:0] not_do_cos_i_fu_612_p2;
reg   [0:0] not_do_cos_i_reg_1270;
wire   [31:0] tmp_99_i_fu_629_p1;
reg   [31:0] tmp_99_i_reg_1276;
wire    ap_CS_fsm_state17;
reg   [48:0] tmp_94_i_reg_1293;
wire    ap_CS_fsm_state18;
reg  signed [51:0] hls_hotbm_fourth_o_29_reg_1299;
reg  signed [43:0] hls_hotbm_fourth_o_31_reg_1304;
wire   [97:0] OP2_V_fu_645_p1;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state22;
reg   [41:0] tmp_96_i_reg_1351;
wire    ap_CS_fsm_state23;
reg   [34:0] tmp_98_i_reg_1356;
reg   [58:0] p_Val2_19_reg_1361;
reg   [55:0] tmp_23_i_reg_1366;
reg   [47:0] tmp_25_i_reg_1371;
reg   [32:0] hls_hotbm_fourth_o_33_reg_1376;
reg   [24:0] hls_hotbm_fourth_o_35_reg_1381;
wire    ap_CS_fsm_state24;
wire   [63:0] p_Val2_22_fu_770_p2;
reg   [63:0] p_Val2_22_reg_1406;
reg   [36:0] tmp_1_reg_1411;
wire    ap_CS_fsm_state25;
reg   [28:0] tmp_2_reg_1416;
wire   [0:0] cos_basis_fu_801_p3;
reg   [0:0] cos_basis_reg_1421;
wire    ap_CS_fsm_state26;
wire   [62:0] Mx_V_read_assign_fu_807_p3;
reg   [62:0] Mx_V_read_assign_reg_1427;
wire   [63:0] r_V_3_fu_825_p2;
reg  signed [63:0] r_V_3_reg_1432;
wire    ap_CS_fsm_state27;
reg   [62:0] result_V_reg_1447;
wire    ap_CS_fsm_state31;
wire  signed [12:0] tmp_54_cast_fu_870_p1;
reg   [12:0] tmp_54_cast_reg_1452;
wire    grp_scaled_fixed2ieee_fu_260_ap_start;
wire    grp_scaled_fixed2ieee_fu_260_ap_done;
wire    grp_scaled_fixed2ieee_fu_260_ap_idle;
wire    grp_scaled_fixed2ieee_fu_260_ap_ready;
wire   [63:0] grp_scaled_fixed2ieee_fu_260_ap_return;
reg    ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start;
wire    ap_CS_fsm_state32;
wire   [31:0] tmp_i2_i_fu_320_p1;
wire   [63:0] p_Val2_s_fu_266_p1;
wire   [10:0] addr_V_fu_304_p3;
wire   [3:0] p_Result_i_i_fu_310_p4;
wire   [255:0] tmp_52_i_i_fu_329_p1;
wire   [255:0] r_V_4_fu_332_p2;
wire   [52:0] p_Result_20_fu_347_p3;
wire   [169:0] grp_fu_361_p0;
wire   [52:0] grp_fu_361_p1;
wire   [222:0] grp_fu_361_p2;
wire   [60:0] p_Result_i3_i_fu_417_p4;
wire   [61:0] p_Result_21_fu_427_p3;
reg   [61:0] p_Result_22_fu_435_p4;
wire   [63:0] p_Result_23_fu_445_p3;
reg   [63:0] tmp_i4_i_fu_453_p3;
wire   [123:0] tmp_65_i_fu_481_p1;
wire   [123:0] p_Val2_13_fu_484_p2;
wire   [10:0] storemerge_i_fu_475_p3;
wire   [10:0] tmp_68_i_fu_499_p1;
wire  signed [11:0] sh_cast_fu_508_p1;
wire   [11:0] tmp_70_i_fu_520_p2;
wire  signed [31:0] sh_assign_4_cast_fu_534_p1;
wire   [62:0] tmp_71_i_fu_537_p1;
wire   [62:0] tmp_72_i_fu_541_p2;
wire   [62:0] tmp_73_i_fu_546_p2;
wire   [62:0] p_Val2_14_fu_551_p3;
wire   [48:0] grp_fu_585_p0;
wire   [48:0] grp_fu_585_p1;
wire   [0:0] not_do_cos_i_fu_612_p0;
wire   [0:0] sin_basis_fu_618_p2;
wire   [7:0] p_Result_24_fu_622_p3;
wire   [97:0] grp_fu_585_p2;
wire   [48:0] grp_fu_648_p0;
wire   [48:0] grp_fu_648_p1;
wire   [48:0] grp_fu_653_p0;
wire   [48:0] grp_fu_653_p1;
wire   [55:0] grp_fu_665_p0;
wire   [48:0] grp_fu_677_p0;
wire   [97:0] grp_fu_648_p2;
wire   [97:0] grp_fu_653_p2;
wire   [107:0] grp_fu_665_p2;
wire   [92:0] grp_fu_677_p2;
wire   [41:0] grp_fu_736_p0;
wire   [32:0] grp_fu_736_p1;
wire   [34:0] grp_fu_748_p0;
wire   [24:0] grp_fu_748_p1;
wire   [62:0] p_Val2_20_fu_723_p3;
wire  signed [63:0] tmp_101_i_fu_754_p1;
wire  signed [63:0] tmp_102_i_fu_758_p1;
wire   [63:0] p_Val2_21_fu_761_p2;
wire  signed [63:0] tmp_104_i_cast_fu_767_p1;
wire   [74:0] grp_fu_736_p2;
wire   [59:0] grp_fu_748_p2;
wire   [0:0] cos_basis_fu_801_p0;
wire   [0:0] tmp_s_fu_796_p2;
wire   [63:0] tmp_106_i_cast_fu_814_p1;
wire   [63:0] p_Val2_23_fu_817_p2;
wire   [63:0] tmp_108_i_cast_fu_822_p1;
wire   [62:0] grp_fu_837_p1;
wire   [125:0] grp_fu_837_p2;
wire   [10:0] p_Ex_V_ret_fu_843_p3;
wire  signed [11:0] rhs_V_fu_860_p1;
wire   [11:0] r_V_fu_864_p2;
wire   [63:0] p_Val2_25_fu_875_p1;
wire   [3:0] p_Result_26_fu_901_p3;
wire   [0:0] tmp_3_fu_907_p18;
wire   [0:0] tmp_4_fu_945_p18;
wire   [0:0] tmp_5_fu_983_p3;
wire   [0:0] p_Result_25_fu_879_p3;
wire   [0:0] p_cast_cast_fu_1004_p0;
wire   [0:0] p_Result_s_fu_990_p2;
wire   [0:0] not_tmp_s_fu_1011_p2;
wire   [10:0] loc_V_2_fu_887_p4;
wire   [0:0] or_cond_fu_996_p2;
wire   [0:0] p_Result_1_fu_1000_p2;
wire   [0:0] p_Result_s_55_fu_1016_p2;
wire   [10:0] p_cast_cast_fu_1004_p3;
wire   [10:0] p_Result_2_fu_1022_p3;
wire   [0:0] not_or_cond_demorgan_fu_1045_p2;
wire   [0:0] not_or_cond_fu_1049_p2;
wire   [0:0] tmp_9_fu_1063_p2;
wire   [51:0] p_Result_3_cast_fu_1055_p3;
wire   [51:0] loc_V_3_fu_897_p1;
wire   [0:0] p_Result_s_56_fu_1029_p3;
wire   [10:0] ret_V_6_fu_1037_p3;
wire   [51:0] ret_V_7_fu_1068_p3;
wire   [63:0] p_Result_27_fu_1076_p4;
wire   [63:0] ret_i_i_fu_1086_p1;
reg   [63:0] ap_return_preg;
reg   [31:0] ap_NS_fsm;
wire   [222:0] grp_fu_361_p00;
wire   [222:0] grp_fu_361_p10;
wire   [107:0] grp_fu_665_p00;
wire   [92:0] grp_fu_677_p00;
wire   [74:0] grp_fu_736_p00;
wire   [74:0] grp_fu_736_p10;
wire   [59:0] grp_fu_748_p00;
wire   [59:0] grp_fu_748_p10;
wire   [125:0] grp_fu_837_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 32'd1;
#0 ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start = 1'b0;
#0 ap_return_preg = 64'd0;
end

sin_or_cos_doublecud #(
    .DataWidth( 256 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
hls_ref_4oPi_table_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_ref_4oPi_table_s_address0),
    .ce0(hls_ref_4oPi_table_s_ce0),
    .q0(hls_ref_4oPi_table_s_q0)
);

sin_or_cos_doubledEe #(
    .DataWidth( 59 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_fourth_o_19_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_fourth_o_19_address0),
    .ce0(hls_hotbm_fourth_o_19_ce0),
    .q0(hls_hotbm_fourth_o_19_q0)
);

sin_or_cos_doubleeOg #(
    .DataWidth( 52 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_fourth_o_20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_fourth_o_20_address0),
    .ce0(hls_hotbm_fourth_o_20_ce0),
    .q0(hls_hotbm_fourth_o_20_q0)
);

sin_or_cos_doublefYi #(
    .DataWidth( 44 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_fourth_o_21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_fourth_o_21_address0),
    .ce0(hls_hotbm_fourth_o_21_ce0),
    .q0(hls_hotbm_fourth_o_21_q0)
);

sin_or_cos_doubleg8j #(
    .DataWidth( 33 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_fourth_o_27_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_fourth_o_27_address0),
    .ce0(hls_hotbm_fourth_o_27_ce0),
    .q0(hls_hotbm_fourth_o_27_q0)
);

sin_or_cos_doublehbi #(
    .DataWidth( 25 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
hls_hotbm_fourth_o_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hls_hotbm_fourth_o_address0),
    .ce0(hls_hotbm_fourth_o_ce0),
    .q0(hls_hotbm_fourth_o_q0)
);

scaled_fixed2ieee grp_scaled_fixed2ieee_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_scaled_fixed2ieee_fu_260_ap_start),
    .ap_done(grp_scaled_fixed2ieee_fu_260_ap_done),
    .ap_idle(grp_scaled_fixed2ieee_fu_260_ap_idle),
    .ap_ready(grp_scaled_fixed2ieee_fu_260_ap_ready),
    .in_V(result_V_reg_1447),
    .prescale(tmp_54_cast_reg_1452),
    .ap_return(grp_scaled_fixed2ieee_fu_260_ap_return)
);

houghTransform_muibs #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 170 ),
    .din1_WIDTH( 53 ),
    .dout_WIDTH( 223 ))
houghTransform_muibs_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_361_p0),
    .din1(grp_fu_361_p1),
    .ce(1'b1),
    .dout(grp_fu_361_p2)
);

houghTransform_mujbC #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
houghTransform_mujbC_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_585_p0),
    .din1(grp_fu_585_p1),
    .ce(1'b1),
    .dout(grp_fu_585_p2)
);

houghTransform_mukbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
houghTransform_mukbM_U6(
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd1),
    .din4(1'd0),
    .din5(1'd0),
    .din6(1'd1),
    .din7(1'd1),
    .din8(1'd0),
    .din9(p_Val2_29_reg_1168),
    .dout(tmp_fu_591_p10)
);

houghTransform_mujbC #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
houghTransform_mujbC_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_648_p0),
    .din1(grp_fu_648_p1),
    .ce(1'b1),
    .dout(grp_fu_648_p2)
);

houghTransform_mujbC #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
houghTransform_mujbC_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_653_p0),
    .din1(grp_fu_653_p1),
    .ce(1'b1),
    .dout(grp_fu_653_p2)
);

houghTransform_mulbW #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 56 ),
    .din1_WIDTH( 52 ),
    .dout_WIDTH( 108 ))
houghTransform_mulbW_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_665_p0),
    .din1(hls_hotbm_fourth_o_29_reg_1299),
    .ce(1'b1),
    .dout(grp_fu_665_p2)
);

houghTransform_mumb6 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 44 ),
    .dout_WIDTH( 93 ))
houghTransform_mumb6_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_677_p0),
    .din1(hls_hotbm_fourth_o_31_reg_1304),
    .ce(1'b1),
    .dout(grp_fu_677_p2)
);

houghTransform_muncg #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 42 ),
    .din1_WIDTH( 33 ),
    .dout_WIDTH( 75 ))
houghTransform_muncg_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_736_p0),
    .din1(grp_fu_736_p1),
    .ce(1'b1),
    .dout(grp_fu_736_p2)
);

houghTransform_muocq #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 35 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 60 ))
houghTransform_muocq_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_748_p0),
    .din1(grp_fu_748_p1),
    .ce(1'b1),
    .dout(grp_fu_748_p2)
);

houghTransform_mupcA #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 63 ),
    .dout_WIDTH( 126 ))
houghTransform_mupcA_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_3_reg_1432),
    .din1(grp_fu_837_p1),
    .ce(1'b1),
    .dout(grp_fu_837_p2)
);

houghTransform_muqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
houghTransform_muqcK_U14(
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd1),
    .din8(1'd0),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .din16(1'd0),
    .din17(p_Result_26_fu_901_p3),
    .dout(tmp_3_fu_907_p18)
);

houghTransform_muqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
houghTransform_muqcK_U15(
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd1),
    .din9(1'd1),
    .din10(1'd0),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd1),
    .din15(1'd0),
    .din16(1'd0),
    .din17(p_Result_26_fu_901_p3),
    .dout(tmp_4_fu_945_p18)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state31)) begin
            ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start <= 1'b1;
        end else if ((1'b1 == grp_scaled_fixed2ieee_fu_260_ap_ready)) begin
            ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state32) & (grp_scaled_fixed2ieee_fu_260_ap_done == 1'b1))) begin
            ap_return_preg <= ret_i_i_fu_1086_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        Ex_V_reg_1220 <= Ex_V_fu_502_p2;
        Mx_V_reg_1213 <= {{p_Val2_13_fu_484_p2[123:61]}};
        isNeg_reg_1225 <= Ex_V_fu_502_p2[32'd10];
        sh_assign_reg_1230 <= sh_assign_fu_526_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        Mx_V_read_assign_reg_1427 <= Mx_V_read_assign_fu_807_p3;
        cos_basis_reg_1421 <= cos_basis_fu_801_p3;
        r_V_3_reg_1432 <= r_V_3_fu_825_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        Mx_zeros_V_reg_1194 <= Mx_zeros_V_fu_461_p1;
        p_Val2_11_reg_1189 <= p_Val2_11_fu_412_p3;
        tmp_6_reg_1200 <= tmp_6_fu_465_p2;
        tmp_8_reg_1206 <= tmp_8_fu_470_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        OP1_V_reg_1250[48 : 0] <= OP1_V_fu_582_p1[48 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        closepath_reg_1109 <= closepath_fu_292_p2;
        expv_op_reg_1116 <= expv_op_fu_298_p2;
        loc_V_1_reg_1103 <= loc_V_1_fu_288_p1;
        loc_V_reg_1096 <= {{p_Val2_s_fu_266_p1[62:52]}};
        p_Result_19_reg_1090 <= p_Val2_s_fu_266_p1[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        hls_hotbm_fourth_o_29_reg_1299 <= hls_hotbm_fourth_o_20_q0;
        hls_hotbm_fourth_o_31_reg_1304 <= hls_hotbm_fourth_o_21_q0;
        tmp_94_i_reg_1293 <= {{grp_fu_585_p2[97:49]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        hls_hotbm_fourth_o_33_reg_1376 <= hls_hotbm_fourth_o_27_q0;
        hls_hotbm_fourth_o_35_reg_1381 <= hls_hotbm_fourth_o_q0;
        p_Val2_19_reg_1361 <= hls_hotbm_fourth_o_19_q0;
        tmp_23_i_reg_1366 <= {{grp_fu_665_p2[107:52]}};
        tmp_25_i_reg_1371 <= {{grp_fu_677_p2[92:45]}};
        tmp_96_i_reg_1351 <= {{grp_fu_648_p2[97:56]}};
        tmp_98_i_reg_1356 <= {{grp_fu_653_p2[97:63]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        not_do_cos_i_reg_1270 <= not_do_cos_i_fu_612_p2;
        tmp_reg_1263 <= tmp_fu_591_p10;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_Result_i_reg_1235 <= {{p_Val2_14_fu_551_p3[62:56]}};
        p_Val2_15_reg_1240 <= p_Val2_15_fu_568_p1;
        tmp_i1_reg_1245 <= {{p_Val2_14_fu_551_p3[55:7]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        p_Val2_22_reg_1406 <= p_Val2_22_fu_770_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        p_Val2_29_reg_1168 <= p_Val2_29_fu_392_p3;
        p_Val2_i_reg_1179 <= p_Val2_i_fu_402_p2;
        tmp_13_reg_1174 <= tmp_13_fu_398_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_Val2_9_reg_1157 <= {{grp_fu_361_p2[166:43]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        result_V_reg_1447 <= {{grp_fu_837_p2[125:63]}};
        tmp_54_cast_reg_1452 <= tmp_54_cast_fu_870_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ret_V_reg_1136 <= {{r_V_4_fu_332_p2[255:86]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        table_256_V_reg_1131 <= hls_ref_4oPi_table_s_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_12_reg_1126 <= tmp_12_fu_325_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        tmp_1_reg_1411 <= {{grp_fu_736_p2[74:38]}};
        tmp_2_reg_1416 <= {{grp_fu_748_p2[59:31]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (closepath_reg_1109 == 1'd0))) begin
        tmp_64_i_reg_1163 <= {{grp_fu_361_p2[169:167]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_7_reg_1151 <= tmp_7_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tmp_99_i_reg_1276[7 : 0] <= tmp_99_i_fu_629_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (closepath_reg_1109 == 1'd1))) begin
        tmp_i_reg_1184 <= tmp_i_fu_407_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state32) & (grp_scaled_fixed2ieee_fu_260_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) & (grp_scaled_fixed2ieee_fu_260_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) & (grp_scaled_fixed2ieee_fu_260_ap_done == 1'b1))) begin
        ap_return = ret_i_i_fu_1086_p1;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        hls_hotbm_fourth_o_19_ce0 = 1'b1;
    end else begin
        hls_hotbm_fourth_o_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        hls_hotbm_fourth_o_20_ce0 = 1'b1;
    end else begin
        hls_hotbm_fourth_o_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        hls_hotbm_fourth_o_21_ce0 = 1'b1;
    end else begin
        hls_hotbm_fourth_o_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        hls_hotbm_fourth_o_27_ce0 = 1'b1;
    end else begin
        hls_hotbm_fourth_o_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        hls_hotbm_fourth_o_ce0 = 1'b1;
    end else begin
        hls_hotbm_fourth_o_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        hls_ref_4oPi_table_s_ce0 = 1'b1;
    end else begin
        hls_ref_4oPi_table_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((1'b1 == ap_CS_fsm_state32) & (grp_scaled_fixed2ieee_fu_260_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Ex_V_fu_502_p2 = (storemerge_i_fu_475_p3 - tmp_68_i_fu_499_p1);

assign Mx_V_read_assign_fu_807_p3 = ((cos_basis_fu_801_p3[0:0] === 1'b1) ? 63'd9223372036854775807 : Mx_V_reg_1213);

assign Mx_zeros_V_fu_461_p1 = tmp_i4_i_fu_453_p3[5:0];

assign OP1_V_fu_582_p1 = tmp_i1_reg_1245;

assign OP2_V_fu_645_p1 = tmp_94_i_reg_1293;

assign addr_V_fu_304_p3 = ((closepath_reg_1109[0:0] === 1'b1) ? 11'd74 : expv_op_reg_1116);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign closepath_fu_292_p2 = ((loc_V_fu_278_p4 < 11'd1022) ? 1'b1 : 1'b0);

assign cos_basis_fu_801_p0 = do_cos;

assign cos_basis_fu_801_p3 = ((cos_basis_fu_801_p0[0:0] === 1'b1) ? tmp_s_fu_796_p2 : tmp_reg_1263);

assign expv_op_fu_298_p2 = ($signed(11'd1101) + $signed(loc_V_fu_278_p4));

assign grp_fu_361_p0 = grp_fu_361_p00;

assign grp_fu_361_p00 = ret_V_reg_1136;

assign grp_fu_361_p1 = grp_fu_361_p10;

assign grp_fu_361_p10 = p_Result_20_fu_347_p3;

assign grp_fu_585_p0 = OP1_V_fu_582_p1;

assign grp_fu_585_p1 = OP1_V_fu_582_p1;

assign grp_fu_648_p0 = OP2_V_fu_645_p1;

assign grp_fu_648_p1 = OP1_V_reg_1250;

assign grp_fu_653_p0 = OP2_V_fu_645_p1;

assign grp_fu_653_p1 = OP2_V_fu_645_p1;

assign grp_fu_665_p0 = grp_fu_665_p00;

assign grp_fu_665_p00 = p_Val2_15_reg_1240;

assign grp_fu_677_p0 = grp_fu_677_p00;

assign grp_fu_677_p00 = tmp_94_i_reg_1293;

assign grp_fu_736_p0 = grp_fu_736_p00;

assign grp_fu_736_p00 = tmp_96_i_reg_1351;

assign grp_fu_736_p1 = grp_fu_736_p10;

assign grp_fu_736_p10 = hls_hotbm_fourth_o_33_reg_1376;

assign grp_fu_748_p0 = grp_fu_748_p00;

assign grp_fu_748_p00 = tmp_98_i_reg_1356;

assign grp_fu_748_p1 = grp_fu_748_p10;

assign grp_fu_748_p10 = hls_hotbm_fourth_o_35_reg_1381;

assign grp_fu_837_p1 = grp_fu_837_p10;

assign grp_fu_837_p10 = Mx_V_read_assign_reg_1427;

assign grp_scaled_fixed2ieee_fu_260_ap_start = ap_reg_grp_scaled_fixed2ieee_fu_260_ap_start;

assign hls_hotbm_fourth_o_19_address0 = tmp_99_i_reg_1276;

assign hls_hotbm_fourth_o_20_address0 = tmp_99_i_fu_629_p1;

assign hls_hotbm_fourth_o_21_address0 = tmp_99_i_fu_629_p1;

assign hls_hotbm_fourth_o_27_address0 = tmp_99_i_reg_1276;

assign hls_hotbm_fourth_o_address0 = tmp_99_i_reg_1276;

assign hls_ref_4oPi_table_s_address0 = tmp_i2_i_fu_320_p1;

assign isNeg_fu_512_p3 = Ex_V_fu_502_p2[32'd10];

assign loc_V_1_fu_288_p1 = p_Val2_s_fu_266_p1[51:0];

assign loc_V_2_fu_887_p4 = {{p_Val2_25_fu_875_p1[62:52]}};

assign loc_V_3_fu_897_p1 = p_Val2_25_fu_875_p1[51:0];

assign loc_V_fu_278_p4 = {{p_Val2_s_fu_266_p1[62:52]}};

assign not_do_cos_i_fu_612_p0 = do_cos;

assign not_do_cos_i_fu_612_p2 = (not_do_cos_i_fu_612_p0 ^ 1'd1);

assign not_or_cond_demorgan_fu_1045_p2 = (tmp_6_reg_1200 & tmp_7_reg_1151);

assign not_or_cond_fu_1049_p2 = (not_or_cond_demorgan_fu_1045_p2 ^ 1'd1);

assign not_tmp_s_fu_1011_p2 = (tmp_8_reg_1206 ^ 1'd1);

assign or_cond_fu_996_p2 = (tmp_6_reg_1200 & tmp_7_reg_1151);

assign p_Ex_V_ret_fu_843_p3 = ((cos_basis_reg_1421[0:0] === 1'b1) ? 11'd0 : Ex_V_reg_1220);

assign p_Result_1_fu_1000_p2 = (p_Result_19_reg_1090 & not_do_cos_i_reg_1270);

assign p_Result_20_fu_347_p3 = {{1'd1}, {loc_V_1_reg_1103}};

assign p_Result_21_fu_427_p3 = {{p_Result_i3_i_fu_417_p4}, {1'd1}};

integer ap_tvar_int_0;

always @ (p_Result_21_fu_427_p3) begin
    for (ap_tvar_int_0 = 62 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 61 - 0) begin
            p_Result_22_fu_435_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_22_fu_435_p4[ap_tvar_int_0] = p_Result_21_fu_427_p3[61 - ap_tvar_int_0];
        end
    end
end

assign p_Result_23_fu_445_p3 = {{2'd3}, {p_Result_22_fu_435_p4}};

assign p_Result_24_fu_622_p3 = {{sin_basis_fu_618_p2}, {p_Result_i_reg_1235}};

assign p_Result_25_fu_879_p3 = p_Val2_25_fu_875_p1[32'd63];

assign p_Result_26_fu_901_p3 = {{p_Result_19_reg_1090}, {p_Val2_29_reg_1168}};

assign p_Result_27_fu_1076_p4 = {{{p_Result_s_56_fu_1029_p3}, {ret_V_6_fu_1037_p3}}, {ret_V_7_fu_1068_p3}};

assign p_Result_2_fu_1022_p3 = ((tmp_8_reg_1206[0:0] === 1'b1) ? 11'd2047 : loc_V_2_fu_887_p4);

assign p_Result_3_cast_fu_1055_p3 = ((not_or_cond_fu_1049_p2[0:0] === 1'b1) ? 52'd4503599627370495 : 52'd0);

assign p_Result_i3_i_fu_417_p4 = {{p_Val2_11_fu_412_p3[123:63]}};

assign p_Result_i_i_fu_310_p4 = {{addr_V_fu_304_p3[10:7]}};

assign p_Result_s_55_fu_1016_p2 = (p_Result_s_fu_990_p2 & not_tmp_s_fu_1011_p2);

assign p_Result_s_56_fu_1029_p3 = ((or_cond_fu_996_p2[0:0] === 1'b1) ? p_Result_1_fu_1000_p2 : p_Result_s_55_fu_1016_p2);

assign p_Result_s_fu_990_p2 = (tmp_5_fu_983_p3 | p_Result_25_fu_879_p3);

assign p_Val2_11_fu_412_p3 = ((tmp_13_reg_1174[0:0] === 1'b1) ? p_Val2_i_reg_1179 : p_Val2_9_reg_1157);

assign p_Val2_13_fu_484_p2 = p_Val2_11_reg_1189 << tmp_65_i_fu_481_p1;

assign p_Val2_14_fu_551_p3 = ((isNeg_reg_1225[0:0] === 1'b1) ? tmp_72_i_fu_541_p2 : tmp_73_i_fu_546_p2);

assign p_Val2_15_fu_568_p1 = p_Val2_14_fu_551_p3[55:0];

assign p_Val2_20_fu_723_p3 = {{p_Val2_19_reg_1361}, {4'd0}};

assign p_Val2_21_fu_761_p2 = ($signed(tmp_101_i_fu_754_p1) + $signed(tmp_102_i_fu_758_p1));

assign p_Val2_22_fu_770_p2 = ($signed(p_Val2_21_fu_761_p2) + $signed(tmp_104_i_cast_fu_767_p1));

assign p_Val2_23_fu_817_p2 = (p_Val2_22_reg_1406 + tmp_106_i_cast_fu_814_p1);

assign p_Val2_25_fu_875_p1 = grp_scaled_fixed2ieee_fu_260_ap_return;

assign p_Val2_29_fu_392_p3 = ((closepath_reg_1109[0:0] === 1'b1) ? 3'd0 : tmp_64_i_reg_1163);

assign p_Val2_i_fu_402_p2 = (124'd0 - p_Val2_9_reg_1157);

assign p_Val2_s_fu_266_p1 = t_in;

assign p_cast_cast_fu_1004_p0 = do_cos;

assign p_cast_cast_fu_1004_p3 = ((p_cast_cast_fu_1004_p0[0:0] === 1'b1) ? 11'd1023 : 11'd0);

assign r_V_3_fu_825_p2 = (p_Val2_23_fu_817_p2 + tmp_108_i_cast_fu_822_p1);

assign r_V_4_fu_332_p2 = table_256_V_reg_1131 << tmp_52_i_i_fu_329_p1;

assign r_V_fu_864_p2 = ($signed(12'd0) - $signed(rhs_V_fu_860_p1));

assign ret_V_6_fu_1037_p3 = ((or_cond_fu_996_p2[0:0] === 1'b1) ? p_cast_cast_fu_1004_p3 : p_Result_2_fu_1022_p3);

assign ret_V_7_fu_1068_p3 = ((tmp_9_fu_1063_p2[0:0] === 1'b1) ? p_Result_3_cast_fu_1055_p3 : loc_V_3_fu_897_p1);

assign ret_i_i_fu_1086_p1 = p_Result_27_fu_1076_p4;

assign rhs_V_fu_860_p1 = $signed(p_Ex_V_ret_fu_843_p3);

assign sh_assign_4_cast_fu_534_p1 = $signed(sh_assign_reg_1230);

assign sh_assign_fu_526_p3 = ((isNeg_fu_512_p3[0:0] === 1'b1) ? tmp_70_i_fu_520_p2 : sh_cast_fu_508_p1);

assign sh_cast_fu_508_p1 = $signed(Ex_V_fu_502_p2);

assign sin_basis_fu_618_p2 = (tmp_reg_1263 ^ not_do_cos_i_reg_1270);

assign storemerge_i_fu_475_p3 = ((closepath_reg_1109[0:0] === 1'b1) ? tmp_i_reg_1184 : 11'd0);

assign tmp_101_i_fu_754_p1 = $signed(p_Val2_20_fu_723_p3);

assign tmp_102_i_fu_758_p1 = $signed(tmp_23_i_reg_1366);

assign tmp_104_i_cast_fu_767_p1 = $signed(tmp_25_i_reg_1371);

assign tmp_106_i_cast_fu_814_p1 = tmp_1_reg_1411;

assign tmp_108_i_cast_fu_822_p1 = tmp_2_reg_1416;

assign tmp_12_fu_325_p1 = addr_V_fu_304_p3[6:0];

assign tmp_13_fu_398_p1 = p_Val2_29_fu_392_p3[0:0];

assign tmp_52_i_i_fu_329_p1 = tmp_12_reg_1126;

assign tmp_54_cast_fu_870_p1 = $signed(r_V_fu_864_p2);

assign tmp_5_fu_983_p3 = ((cos_basis_reg_1421[0:0] === 1'b1) ? tmp_3_fu_907_p18 : tmp_4_fu_945_p18);

assign tmp_65_i_fu_481_p1 = Mx_zeros_V_reg_1194;

assign tmp_68_i_fu_499_p1 = Mx_zeros_V_reg_1194;

assign tmp_6_fu_465_p2 = ((loc_V_reg_1096 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_70_i_fu_520_p2 = ($signed(12'd0) - $signed(sh_cast_fu_508_p1));

assign tmp_71_i_fu_537_p1 = $unsigned(sh_assign_4_cast_fu_534_p1);

assign tmp_72_i_fu_541_p2 = Mx_V_reg_1213 >> tmp_71_i_fu_537_p1;

assign tmp_73_i_fu_546_p2 = Mx_V_reg_1213 << tmp_71_i_fu_537_p1;

assign tmp_7_fu_367_p2 = ((loc_V_1_reg_1103 == 52'd0) ? 1'b1 : 1'b0);

assign tmp_8_fu_470_p2 = ((loc_V_reg_1096 == 11'd2047) ? 1'b1 : 1'b0);

assign tmp_99_i_fu_629_p1 = p_Result_24_fu_622_p3;

assign tmp_9_fu_1063_p2 = (or_cond_fu_996_p2 | tmp_8_reg_1206);

assign tmp_i2_i_fu_320_p1 = p_Result_i_i_fu_310_p4;


always @ (p_Result_23_fu_445_p3) begin
    if (p_Result_23_fu_445_p3[0] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd0;
    end else if (p_Result_23_fu_445_p3[1] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd1;
    end else if (p_Result_23_fu_445_p3[2] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd2;
    end else if (p_Result_23_fu_445_p3[3] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd3;
    end else if (p_Result_23_fu_445_p3[4] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd4;
    end else if (p_Result_23_fu_445_p3[5] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd5;
    end else if (p_Result_23_fu_445_p3[6] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd6;
    end else if (p_Result_23_fu_445_p3[7] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd7;
    end else if (p_Result_23_fu_445_p3[8] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd8;
    end else if (p_Result_23_fu_445_p3[9] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd9;
    end else if (p_Result_23_fu_445_p3[10] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd10;
    end else if (p_Result_23_fu_445_p3[11] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd11;
    end else if (p_Result_23_fu_445_p3[12] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd12;
    end else if (p_Result_23_fu_445_p3[13] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd13;
    end else if (p_Result_23_fu_445_p3[14] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd14;
    end else if (p_Result_23_fu_445_p3[15] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd15;
    end else if (p_Result_23_fu_445_p3[16] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd16;
    end else if (p_Result_23_fu_445_p3[17] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd17;
    end else if (p_Result_23_fu_445_p3[18] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd18;
    end else if (p_Result_23_fu_445_p3[19] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd19;
    end else if (p_Result_23_fu_445_p3[20] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd20;
    end else if (p_Result_23_fu_445_p3[21] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd21;
    end else if (p_Result_23_fu_445_p3[22] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd22;
    end else if (p_Result_23_fu_445_p3[23] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd23;
    end else if (p_Result_23_fu_445_p3[24] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd24;
    end else if (p_Result_23_fu_445_p3[25] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd25;
    end else if (p_Result_23_fu_445_p3[26] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd26;
    end else if (p_Result_23_fu_445_p3[27] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd27;
    end else if (p_Result_23_fu_445_p3[28] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd28;
    end else if (p_Result_23_fu_445_p3[29] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd29;
    end else if (p_Result_23_fu_445_p3[30] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd30;
    end else if (p_Result_23_fu_445_p3[31] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd31;
    end else if (p_Result_23_fu_445_p3[32] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd32;
    end else if (p_Result_23_fu_445_p3[33] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd33;
    end else if (p_Result_23_fu_445_p3[34] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd34;
    end else if (p_Result_23_fu_445_p3[35] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd35;
    end else if (p_Result_23_fu_445_p3[36] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd36;
    end else if (p_Result_23_fu_445_p3[37] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd37;
    end else if (p_Result_23_fu_445_p3[38] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd38;
    end else if (p_Result_23_fu_445_p3[39] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd39;
    end else if (p_Result_23_fu_445_p3[40] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd40;
    end else if (p_Result_23_fu_445_p3[41] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd41;
    end else if (p_Result_23_fu_445_p3[42] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd42;
    end else if (p_Result_23_fu_445_p3[43] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd43;
    end else if (p_Result_23_fu_445_p3[44] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd44;
    end else if (p_Result_23_fu_445_p3[45] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd45;
    end else if (p_Result_23_fu_445_p3[46] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd46;
    end else if (p_Result_23_fu_445_p3[47] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd47;
    end else if (p_Result_23_fu_445_p3[48] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd48;
    end else if (p_Result_23_fu_445_p3[49] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd49;
    end else if (p_Result_23_fu_445_p3[50] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd50;
    end else if (p_Result_23_fu_445_p3[51] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd51;
    end else if (p_Result_23_fu_445_p3[52] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd52;
    end else if (p_Result_23_fu_445_p3[53] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd53;
    end else if (p_Result_23_fu_445_p3[54] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd54;
    end else if (p_Result_23_fu_445_p3[55] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd55;
    end else if (p_Result_23_fu_445_p3[56] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd56;
    end else if (p_Result_23_fu_445_p3[57] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd57;
    end else if (p_Result_23_fu_445_p3[58] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd58;
    end else if (p_Result_23_fu_445_p3[59] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd59;
    end else if (p_Result_23_fu_445_p3[60] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd60;
    end else if (p_Result_23_fu_445_p3[61] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd61;
    end else if (p_Result_23_fu_445_p3[62] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd62;
    end else if (p_Result_23_fu_445_p3[63] == 1'b1) begin
        tmp_i4_i_fu_453_p3 = 64'd63;
    end else begin
        tmp_i4_i_fu_453_p3 = 64'd64;
    end
end

assign tmp_i_fu_407_p2 = ($signed(11'd1027) + $signed(loc_V_reg_1096));

assign tmp_s_fu_796_p2 = (tmp_reg_1263 ^ 1'd1);

always @ (posedge ap_clk) begin
    OP1_V_reg_1250[97:49] <= 49'b0000000000000000000000000000000000000000000000000;
    tmp_99_i_reg_1276[31:8] <= 24'b000000000000000000000000;
end

endmodule //sin_or_cos_double_s
